// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Accordion/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.Accordion, { items: [
        { id: 'seller', title: 'Seller', content: h('div', null, h('strong', null, 'SGS Nairobi'), h('div', { style: { color: 'var(--text-secondary)' } }, 'Museum Hill, Kipande Rd, P.O. Box 40658 - 00100, Nairobi')) },
        { id: 'buyer', title: 'Buyer', meta: h(G.Tag, { tone: 'required' }, 'Required'), defaultOpen: true, content: h(G.TextInput, { label: 'Company name', required: true, placeholder: 'Search your companies', helpText: 'Results are from companies used in past transactions.' }) }
      ] }),
      cap('Without action label — e.g. "Affected Products" inside a Document Item'),
      h(G.Accordion, { showActionLabel: false, items: [{ id: 'ap', title: 'Affected Products', content: 'Table of affected products goes here.' }] })
    ));
}

