// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/AppSidebar/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap', style: { width: 'auto' } }, t); }
  var SR = { id: 'sr', label: 'Service Requests', icon: 'task', badge: 2, badgeTone: 'attention', badgeLabel: 'requests need action', children: [
    { id: 'sr-all', label: 'All requests', badge: 2, badgeTone: 'attention', badgeLabel: 'need action' },
    { id: 'sr-cert', label: 'Certification Services' },
    { id: 'sr-train', label: 'Training Courses' },
    { type: 'label', label: 'Other services' },
    { id: 'sr-gap', label: 'Gap Analysis' },
    { id: 'sr-impl', label: 'Implementation Support' } ] };
  var MAIN = [
    { id: 'home', label: 'Home', icon: 'dashboard' },
    { id: 'scopes', label: 'Scopes', icon: 'category' },
    { id: 'ws', label: 'Workspaces', icon: 'folders', badge: 4 },
    { id: 'docs', label: 'Documents', icon: 'document--multiple-01' },
    SR,
    { id: 'training', label: 'Training', icon: 'education' },
    { id: 'audit', label: 'Audit Logs', icon: 'catalog' },
    { id: 'settings', label: 'Settings', icon: 'settings' } ];
  var USER = [{ items: MAIN }];
  var ADMIN = [{ items: MAIN }, { label: 'Administration', items: [
    { id: 'users', label: 'Users', icon: 'user--multiple' },
    { id: 'access', label: 'Workspace access', icon: 'user--access' } ] }];
  function col(title, el){ return h('div', { style: { display: 'flex', flexDirection: 'column', gap: 8, height: 700 } }, cap(title), h('div', { style: { flex: 1, minHeight: 0 } }, el)); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)', flexDirection: 'row', alignItems: 'flex-start', gap: 24 } },
      col('Customer User', h(G.AppSidebar, { label: 'Customer Portal', sections: USER, defaultActive: 'sr-gap' })),
      col('Customer Admin (+ Administration)', h(G.AppSidebar, { label: 'Customer Portal', sections: ADMIN, defaultActive: 'access' })),
      col('Collapsed (72px)', h(G.AppSidebar, { label: 'Customer Portal', sections: ADMIN, defaultActive: 'sr-gap', defaultCollapsed: true }))
    ));
}

