// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Avatar/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      row(h(G.Avatar, { name: 'Linh Tran', size: 'sm' }), h(G.Avatar, { name: 'Linh Tran' }), h(G.Avatar, { name: 'John Doe', size: 'lg' }), h(G.Avatar, { size: 'lg' }))
    ));
}

