// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Breadcrumb/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.Breadcrumb, { items: [{ label: 'Home', href: '#' }, { label: 'Service Requests', href: '#' }, { label: 'SR-2026-04-12345' }] }),
      h(G.Breadcrumb, { items: [{ label: 'Settings', href: '#' }, { label: 'User Profile' }] })
    ));
}

