// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Combobox/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Type to filter, ↑/↓ to move, Enter to choose — e.g. "Company name – Search your companies"'),
      row(h(G.Combobox, { label: 'Company name', required: true, placeholder: 'Search your companies', helpText: 'Results are from companies used in past transactions.', defaultOpen: true, options: [{ value: 'sgs-ke', label: 'SGS Nairobi', description: 'Museum Hill, Kipande Rd, Nairobi' }, { value: 'abc', label: 'ABC Trading Co., Ltd.', description: 'Taipei, Taiwan' }, { value: 'lotus', label: 'Lotus Cosmetics JSC', description: 'Bac Ninh, Vietnam' }, { value: 'riyadh', label: 'Riyadh Imports LLC', description: 'Riyadh, Saudi Arabia' }] }),
        h(G.Combobox, { label: 'Country of destination', size: 's', defaultValue: 'sa', options: [{ value: 'sa', label: 'Saudi Arabia' }, { value: 'ae', label: 'United Arab Emirates' }] }))
    ));
}

