// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/CommentThread/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      h('div', { style: { maxWidth: 420, padding: 16, borderRadius: 16, background: 'var(--layer-extension)' } },
        h(G.CommentThread, { title: 'Messages', count: 3, maxHeight: 300, currentUser: 'Linh Tran', messages: [
          { id: 1, author: 'Minh Nguyen', role: 'sgs', roleLabel: 'SGS reviewer', time: '09:12', body: 'Please upload the latest test report for the face cream. The one attached expired in March.' },
          { id: 2, author: 'Linh Tran', role: 'customer', time: '10:40', body: 'Thanks — uploading the 2026 report now.' },
          { id: 3, author: 'Minh Nguyen', role: 'sgs', roleLabel: 'SGS reviewer', time: '11:05', internal: true, body: 'Internal: lab accreditation checked, OK to proceed once uploaded.' } ] }))
    ));
}

