// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/DatePicker/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Monday-first calendar, today outlined, selected in orange; arrow keys move between days'),
      row(h(G.DatePicker, { label: 'Evidence valid until', required: true, defaultValue: '2026-10-12', today: '2026-09-24', min: '2026-09-24', defaultOpen: true, helpText: 'Past dates are not allowed.' }),
        h(G.DatePicker, { label: 'Audit date', placeholder: 'DD MMM YYYY', today: '2026-09-24' }))
    ));
}

