// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/DocumentItem/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      cap('Standard · Completed'),
      h(G.DocumentItem, { docType: 'Final Invoice', fileName: 'invoice234657.pdf', dateLabel: 'Uploaded January 20, 2026', size: '2.4 MB', status: 'completed', actions: [{ type: 'edit' }, { type: 'open' }, { type: 'delete' }] }),
      cap('Under Review — subdued, read-only actions'),
      h(G.DocumentItem, { variant: 'under-review', docType: 'Final Invoice', fileName: 'invoice234657.pdf', dateLabel: 'Uploaded January 20, 2026', size: '2.4 MB', status: 'under-review', actions: [{ type: 'open' }, { type: 'view' }] }),
      cap('Actions Required / Missing Info — dashed orange, Affected Products expands (Area 5)'),
      h(G.DocumentItem, { variant: 'actions-required', docType: 'Test Report', status: 'missing-info', defaultExpanded: true, actions: [{ type: 'upload' }] },
        h(G.Table, { density: 'compact', columns: [{ key: 'p', header: 'Product' }, { key: 'm', header: 'Model' }, { key: 'q', header: 'Qty', align: 'end' }], rows: [{ p: 'Face cream 50 ml', m: 'FC-50', q: 1200 }, { p: 'Lip balm', m: 'LB-10', q: 800 }] })),
      cap('SGS Documents — blue, no leading icon'),
      h(G.DocumentItem, { variant: 'sgs', docType: 'Inspection Results', fileName: 'IR-2026-001245.pdf', dateLabel: 'Issued April 15, 2026', size: '2.4 MB', actions: [{ type: 'open' }, { type: 'download' }] }),
      cap('Small breakpoint — no icon, status icon-only, actions in one overflow, metadata truncated (tooltip)'),
      h('div', { style: { width: 340 } }, h(G.DocumentItem, { compact: true, docType: 'Final Invoice', fileName: 'invoice234657.pdf', dateLabel: 'Uploaded January 20, 2026', size: '2.4 MB', status: 'completed', actions: [{ type: 'edit' }, { type: 'open' }, { type: 'delete' }] }))
    ));
}

