// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Drawer/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  function Demo(){ var s = React.useState(false); return h('div', null, h(G.Button, { size: 'md', variant: 'secondary', onClick: function(){ s[1](true); } }, 'Open real drawer'), h(G.Drawer, { open: s[0], title: 'Review comment', onClose: function(){ s[1](false); } }, 'Drawer content')); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h('div', { style: { position: 'relative', height: 380, borderRadius: 8, overflow: 'hidden', background: 'var(--background)' } },
        h(G.Drawer, { inline: true, open: true, title: 'Evidence details', subtitle: 'Information security policy', onClose: function(){},
          footer: h(React.Fragment, null, h(G.Button, { variant: 'ghost', size: 'md' }, 'Cancel'), h(G.Button, { size: 'md' }, 'Save')) },
          h('div', { style: { display: 'flex', flexDirection: 'column', gap: 16 } }, h(G.StatusTag, { status: 'under-review', size: 'sm' }), h(G.Textarea, { label: 'Description', width: '100%', defaultValue: 'Approved ISMS policy v3, signed by the CISO on 12 Jan 2026.' })))),
      h(Demo)
    ));
}

