// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/EmptyState/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.EmptyState, { icon: 'folder', title: 'No evidence yet', body: 'Upload documents that show how you meet this requirement. SGS reviewers see them once you submit.', action: h(G.Button, { size: 'md', icon: 'upload', iconPosition: 'left' }, 'Upload evidence') }),
      h(G.EmptyState, { size: 'sm', title: 'No comments', body: 'Messages from your SGS reviewer appear here.' })
    ));
}

