// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/FileUpload/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.FileUpload, { label: 'Supporting documents', required: true, maxSizeMB: 20, defaultFiles: [
        { name: 'invoice234657.pdf', size: 2516582, status: 'complete' },
        { name: 'test-report-2026.pdf', size: 5400000, status: 'uploading', progress: 62 },
        { name: 'packing-list.xlsx', size: 812000, status: 'scanning' },
        { name: 'factory-photos.zip', size: 48000000, status: 'error', error: 'File is larger than 20 MB. Split it or contact support.' } ] })
    ));
}

