// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/FormField/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Anatomy: label (+ orange * when required) · field · one message below (help text OR error)'),
      h(G.TextInput, { label: 'Company name', required: true, placeholder: 'Search your companies', helpText: 'Results are from companies used in past transactions.' }),
      cap('Error replaces the help text; typing removes it immediately'),
      h(G.TextInput, { label: 'Email', required: true, defaultValue: 'linh.tran@sgs', error: 'Enter a valid email address.' }),
      cap('Disabled'),
      h(G.TextInput, { label: 'Tax ID', disabled: true, placeholder: 'Not editable', helpText: 'Set by SGS after onboarding.' })
    ));
}

