// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/IconButton/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Ghost (default) · primary · secondary — always carries a label (aria-label + tooltip)'),
      row(h(G.IconButton, { icon: 'close', label: 'Close' }), h(G.IconButton, { icon: 'add', label: 'Add', variant: 'primary' }), h(G.IconButton, { icon: 'arrow--right', label: 'Next', variant: 'secondary' }), h(G.IconButton, { icon: 'search', label: 'Search', size: 'md' }), h(G.IconButton, { icon: 'add', label: 'Add', variant: 'primary', disabled: true }))
    ));
}

