// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/InlineNotification/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h('div', { style: { maxWidth: 320 } }, h(G.InlineNotification, { kind: 'warning', title: 'Required Information', items: ['Buyer company', 'Payer assignment', 'Payer Tax ID', 'CoC Collector'] })),
      h(G.InlineNotification, { kind: 'error', title: 'Action required: Upload requested documents', onClose: function(){} }, 'The reviewer asked for 2 more documents before the audit can be scheduled.'),
      h(G.InlineNotification, { kind: 'info', title: 'Need help?', action: h(G.Button, { variant: 'tertiary', size: 'sm' }, 'Contact Support') }, 'Contact SGS support for assistance with your service request creation.'),
      h(G.InlineNotification, { kind: 'success', title: 'Certificate issued' }, 'ISO/IEC 27001 certificate CN-2026-00412 is now valid until 14 Sep 2029.')
    ));
}

