// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/LanguageSelector/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { minHeight: 212 } },
      cap('Top bar, right side. Default shows code + native name; compact (small breakpoints) shows the code only.'),
      h('div', { style: { display: 'flex', gap: 200, alignItems: 'flex-start' } },
        h(G.LanguageSelector, { defaultOpen: true, align: 'start' }),
        h(G.LanguageSelector, { compact: true, defaultValue: 'zh-Hant' }))
    ));
}

