// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Link/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Standalone · semibold'),
      row(h(G.Link, null, 'Forgot your password?'), h(G.Link, { weight: 'semibold' }, 'Contact SGS support')),
      cap('Inside help text: only the interactive part is orange and underlined, never bold'),
      h('div', { style: { fontSize: 12, lineHeight: '20px', color: 'var(--text-secondary)' } }, 'Supported file types are PDF, DOC, and XLS. ', h(G.Link, { inline: true }, 'View requirements.'))
    ));
}

