// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/ListPage/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  var SR = { id: 'sr', label: 'Service Requests', icon: 'task', badge: 1, badgeTone: 'attention', badgeLabel: 'request needs action', children: [
    { id: 'sr-all', label: 'All requests' }, { id: 'sr-cert', label: 'Certification Services' }, { id: 'sr-train', label: 'Training Courses' },
    { type: 'label', label: 'Other services' }, { id: 'sr-gap', label: 'Gap Analysis', badge: 1, badgeTone: 'attention', badgeLabel: 'needs action' }, { id: 'sr-impl', label: 'Implementation Support' } ] };
  var NAV = [{ items: [
    { id: 'home', label: 'Home', icon: 'dashboard' }, { id: 'scopes', label: 'Scopes', icon: 'category' }, { id: 'ws', label: 'Workspaces', icon: 'folders' },
    { id: 'docs', label: 'Documents', icon: 'document--multiple-01' }, SR, { id: 'training', label: 'Training', icon: 'education' },
    { id: 'audit', label: 'Audit Logs', icon: 'catalog' }, { id: 'settings', label: 'Settings', icon: 'settings' } ] },
    { label: 'Administration', items: [{ id: 'users', label: 'Users', icon: 'user--multiple' }, { id: 'access', label: 'Workspace access', icon: 'user--access' }] }];
  function Shell(props){
    return h('div', { style: { width: 1440, height: 900, boxSizing: 'border-box', padding: 12, display: 'flex', flexDirection: 'column', gap: 12, background: 'var(--background)', fontFamily: 'var(--font-sans)', color: 'var(--text-primary)', overflow: 'hidden' } },
      h(G.TopBar, { variant: 'home', siteName: 'Digital Trust Platform', siteSub: 'Customer Portal', userName: 'Linh Tran', userEmail: 'linh.tran@abc-trading.com', notifications: 3 }),
      h('div', { style: { flex: 1, minHeight: 0, display: 'flex', gap: 12 } },
        h('div', { style: { flexShrink: 0 } }, h(G.AppSidebar, { label: 'Customer Portal', sections: NAV, defaultActive: props.active || 'sr-gap', defaultCollapsed: !!props.collapsed })),
        h('main', { style: { flex: 1, minWidth: 0, minHeight: 0, display: 'flex', flexDirection: 'column', gap: 12 } }, props.children)));
  }

  var ROWS = [
    { id: 'GA-2026-004', fw: 'ISO 22301', scope: 'Head office · Taipei', st: 'draft', stl: 'Draft', consultant: '—', updated: '2026-09-22' },
    { id: 'GA-2026-003', fw: 'ISO/IEC 42001', scope: 'AI platform', st: 'missing-info', stl: 'Action required', consultant: 'Minh Nguyen', updated: '2026-09-20' },
    { id: 'GA-2026-002', fw: 'ISO/IEC 27001', scope: 'Head office · Taipei', st: 'under-review', stl: 'In progress', consultant: 'Anna Lee', updated: '2026-09-11' },
    { id: 'GA-2026-001', fw: 'TISAX', scope: 'Plant · Taichung', st: 'completed', stl: 'Report delivered', consultant: 'Minh Nguyen', updated: '2026-06-30' } ];
  var COLS = [
    { key: 'id', header: 'Request', sortable: true, width: 150 },
    { key: 'fw', header: 'Framework', sortable: true },
    { key: 'scope', header: 'Scope', sortable: true },
    { key: 'st', header: 'Status', sortable: true, sortValue: function(r){ return r.stl; }, searchValue: function(r){ return r.stl; }, render: function(r){ return h(G.StatusTag, { status: r.st, size: 'sm', label: r.stl }); } },
    { key: 'consultant', header: 'SGS consultant' },
    { key: 'updated', header: 'Last update', sortable: true, width: 130 } ];

  export default function Preview() {
  return (h(Shell, null,
      h('div', { style: { display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: 24, padding: '8px 8px 4px' } },
        h('div', null,
          h(G.Breadcrumb, { items: [{ label: 'Service Requests', href: '#' }, { label: 'Gap Analysis' }] }),
          h('h1', { className: 'headline-medium', style: { margin: '8px 0 0' } }, 'Gap Analysis'),
          h('p', { className: 'body-medium', style: { margin: 0, color: 'var(--text-secondary)' } }, 'Find out how far you are from a framework before you commit to certification.')),
        h(G.Button, { icon: 'add', iconPosition: 'left' }, 'Request a gap analysis')),
      h(G.InlineNotification, { kind: 'error', title: 'GA-2026-003 needs your input', onClose: function(){} }, 'Your SGS consultant asked for the AI system inventory before the kickoff call.'),
      h('div', { style: { flex: 1, minHeight: 0 } },
        h(G.DataTable, { title: 'My gap analyses', columns: COLS, rows: ROWS, searchable: true, searchPlaceholder: 'Search gap analyses', rowActions: function(){ return [{ label: 'Open' }, { label: 'Message consultant' }, { label: 'Withdraw', danger: true }]; }, pageSize: 10, layout: 'table', defaultSort: { key: 'updated', dir: 'desc' } }))));
}

