// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/MultiSelect/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Selected values show as removable chips; the list stays open while choosing'),
      row(h(G.MultiSelect, { label: 'Role/s', required: true, placeholder: 'No roles selected', defaultValue: ['payer', 'collector'], defaultOpen: true, options: [{ value: 'payer', label: 'Payer' }, { value: 'collector', label: 'CoC Collector' }, { value: 'manufacturer', label: 'Manufacturer' }, { value: 'supplier', label: 'Supplier' }] }),
        h(G.MultiSelect, { label: 'Frameworks', size: 's', placeholder: 'Select frameworks', options: [{ value: '27001', label: 'ISO/IEC 27001' }, { value: '42001', label: 'ISO/IEC 42001' }] }))
    ));
}

