// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/NotificationBadge/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Count on the notification bell; dot for "something new" without a number'),
      row(h(G.NotificationBadge, { count: 3 }, h(G.IconButton, { icon: 'notification', label: 'Notifications' })), h(G.NotificationBadge, { count: 128 }, h(G.IconButton, { icon: 'notification', label: 'Notifications' })), h(G.NotificationBadge, { dot: true, label: 'New messages' }, h(G.IconButton, { icon: 'events', label: 'Communications' })))
    ));
}

