// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/OverflowMenu/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Replaces 4+ actions (and all actions at small breakpoints) with one kebab. Arrow keys, Home/End, Esc.'),
      h('div', { style: { display: 'flex', justifyContent: 'flex-start', gap: 160 } },
        h(G.OverflowMenu, { defaultOpen: true, align: 'start', items: [{ label: 'View description' }, { label: 'Open document' }, { label: 'Replace file' }, { label: 'Delete', danger: true }] }),
        h(G.OverflowMenu, { label: 'Request actions', items: [{ label: 'Duplicate request' }, { label: 'Download summary' }, { label: 'Withdraw', disabled: true }] }))
    ));
}

