// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/PageHeader/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      cap('Standard / large desktop — 32px between title, status and autosave'),
      h(G.PageHeader, { title: 'New Service Request', subtitle: 'Edit, save and submit your requests', onBack: function(){}, status: { status: 'draft', label: 'Draft — not yet submitted', shortLabel: 'Draft' }, autosave: 'saved',
        actions: h(React.Fragment, null, h(G.Button, { variant: 'secondary', size: 'md' }, 'Keep as Draft'), h(G.Button, { size: 'md', disabled: true }, 'Submit Request')) }),
      cap('compact (tablet) — 20px gaps, short status without icon, icon autosave, icon actions'),
      h(G.PageHeader, { compact: true, title: 'New Service Request', subtitle: 'Edit, save and submit your requests', onBack: function(){}, status: { status: 'missing-info', label: 'Action required: Upload requested documents', shortLabel: 'Action required' }, autosave: 'saved',
        compactActions: h(React.Fragment, null, h(G.IconButton, { icon: 'save', label: 'Keep as Draft', variant: 'secondary' }), h(G.IconButton, { icon: 'send', label: 'Submit Request', variant: 'primary', disabled: true })) })
    ));
}

