// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Pagination/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  function Demo(){ var p = React.useState(2), s = React.useState(10);
    return h('div', { style: { background: 'var(--layer-02)', borderRadius: 8 } }, h(G.Pagination, { totalItems: 100, page: p[0], pageSize: s[0], onPageChange: p[1], onPageSizeChange: function(n){ s[1](n); p[1](1); } })); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      cap('Items per page · range · page picker · previous/next (matches the table footer in the SR mockups)'),
      h(Demo),
      cap('First page — previous disabled'),
      h('div', { style: { background: 'var(--layer-02)', borderRadius: 8 } }, h(G.Pagination, { totalItems: 42, page: 1, pageSize: 10, onPageChange: function(){} }))
    ));
}

