// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Popover/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Anchored panel for filters and small forms. Click outside or Esc closes. (Radix Popover)'),
      h(G.Popover, { defaultOpen: true, title: 'Filter requests', trigger: h(G.Button, { variant: 'tertiary', size: 'md' }, 'Filter') },
        h('div', { style: { display: 'flex', flexDirection: 'column' } }, h(G.Checkbox, { label: 'Action required', defaultChecked: true }), h(G.Checkbox, { label: 'Under review' }), h(G.Checkbox, { label: 'Certificate issued' })))
    ));
}

