// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/ProgressBar/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.ProgressBar, { label: 'Readiness · ISO/IEC 27001', value: 64, helperText: '49 of 77 requirements have accepted evidence' }),
      h(G.ProgressBar, { label: 'Upload complete', value: 100 }),
      h(G.ProgressBar, { label: 'Upload failed', value: 38, status: 'error', helperText: 'Connection lost. Try again.' }),
      h(G.ProgressBar, { label: 'Small (file rows)', value: 45, size: 'sm' })
    ));
}

