// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Radio/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h('fieldset', { style: { border: 0, margin: 0, padding: 0 } },
        h('legend', { style: { fontSize: 12, lineHeight: '20px', color: 'var(--text-secondary)' } }, 'Service type ', h('span', { className: 'gr-req' }, '*')),
        row(h(G.Radio, { name: 'svc', label: 'Certification', defaultChecked: true }), h(G.Radio, { name: 'svc', label: 'Training' }), h(G.Radio, { name: 'svc', label: 'Second-party audit' }), h(G.Radio, { name: 'svc2', label: 'Disabled', disabled: true })))
    ));
}

