// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/ReadinessRing/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Share of requirements with accepted evidence. The number is always shown — never colour alone.'),
      row(h(G.ReadinessRing, { value: 82, size: 'lg', label: 'ISO/IEC 27001', caption: '63 of 77 requirements ready' }), h(G.ReadinessRing, { value: 35, label: 'TISAX', caption: '14 of 40 ready' }))
    ));
}

