// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/RequirementNavigator/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  var groups = [
    { id: 'c4', code: '4–10', title: 'Management system', progress: 100, children: [{ id: 'c4.1', code: '4.1', title: 'Understanding the organization and its context', status: 'met' }] },
    { id: 'a5', code: 'A.5', title: 'Organizational controls', progress: 32, children: [
      { id: 'a5.1', code: 'A.5.1', title: 'Policies for information security', status: 'met' },
      { id: 'a5.2', code: 'A.5.2', title: 'Roles and responsibilities', status: 'partial' },
      { id: 'a5.7', code: 'A.5.7', title: 'Threat intelligence', status: 'notmet' },
      { id: 'a5.9', code: 'A.5.9', title: 'Inventory of assets', status: 'notmet' },
      { id: 'a5.10', code: 'A.5.10', title: 'Acceptable use of information' } ] },
    { id: 'a6', code: 'A.6', title: 'People controls', progress: 50, children: [{ id: 'a6.1', code: 'A.6.1', title: 'Screening', status: 'met' }] },
    { id: 'a7', code: 'A.7', title: 'Physical controls', progress: 21, children: [{ id: 'a7.1', code: 'A.7.1', title: 'Physical security perimeters', status: 'partial' }] } ];
  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      h('div', { className: 'gr-demo__cap' }, 'Framework header · search + status filter · one box per clause (with progress) and per requirement (with status). Type to search: groups open automatically.'),
      h('div', { style: { width: 320, padding: 12, boxSizing: 'border-box', borderRadius: 16, background: 'var(--layer-02)' } },
        h(G.RequirementNavigator, { framework: { name: 'ISO/IEC 27001:2022', progress: 36, caption: '42 of 116 assessed' }, groups: groups, defaultExpanded: ['a5'], defaultSelected: 'a5.9' }))));
}

