// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/SearchInput/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Label hidden by default (still announced) · with visible label'),
      row(h(G.SearchInput, { placeholder: 'Search for a Service Request' }), h(G.SearchInput, { showLabel: true, label: 'Filter frameworks', size: 's', placeholder: 'ISO 27001' }))
    ));
}

