// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/SectionNav/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  var SECTIONS = [{ id: 'rd', label: 'Request Details', status: 'complete', icon: 'information' }, { id: 'doc', label: 'Documents', status: 'incomplete', icon: 'folder' }, { id: 'tp', label: 'Trade Parties', status: 'incomplete', icon: 'events' }, { id: 'gi', label: 'Goods Items', status: 'incomplete', icon: 'box' }, { id: 'sd', label: 'Shipment Details', status: 'incomplete', icon: 'delivery' }];
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Left column of SR creation. text ≥1440px · icon 1280–1439px and tablets. Green check = complete, orange dot = required info missing.'),
      row(
        h('div', { style: { width: 200 } }, h(G.SectionNav, { defaultActive: 'tp', items: SECTIONS })),
        h(G.SectionNav, { variant: 'icon', defaultActive: 'tp', items: SECTIONS }))
    ));
}

