// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Select/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Dropdown widths add 68px (48px icon area + 4px right padding)'),
      h(G.Select, { label: 'Who will pay for this service?', required: true, placeholder: 'Select a payer...', helpText: 'List of the Seller and the added parties', options: [{ value: 'seller', label: 'Seller — SGS Nairobi' }, { value: 'buyer', label: 'Buyer' }] }),
      h(G.Select, { label: 'Country of destination', size: 's', defaultValue: 'sa', options: [{ value: 'sa', label: 'Saudi Arabia' }, { value: 'ae', label: 'UAE' }] }),
      h(G.Select, { label: 'Contact', required: true, placeholder: 'No roles selected', error: 'Select a contact.', options: [{ value: 'j', label: 'John Doe' }] })
    ));
}

