// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Separator/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row', style: { alignItems: 'flex-start' } }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Horizontal (default) and vertical — only where layers alone cannot separate content'),
      h(G.Separator, null),
      h('div', { style: { display: 'flex', alignItems: 'center', gap: 16, height: 32, fontSize: 14 } }, 'Title', h(G.Separator, { orientation: 'vertical' }), 'Draft', h(G.Separator, { orientation: 'vertical' }), 'All changes saved')
    ));
}

