// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Snackbar/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  function Demo(){ var s = React.useState(false); return h('div', null, h(G.Button, { size: 'md', variant: 'secondary', onClick: function(){ s[1](true); } }, 'Trigger real snackbar'), h(G.Snackbar, { open: s[0], message: 'All changes saved.', onClose: function(){ s[1](false); } })); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Process feedback: bottom centre, auto-dismiss (5 s default). Inline here for the preview.'),
      h(G.Snackbar, { inline: true, message: 'Draft saved.' }),
      h(G.Snackbar, { inline: true, message: 'Service request submitted.', action: { label: 'View', onClick: function(){} }, onClose: function(){}, duration: 0 }),
      h(Demo)
    ));
}

