// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/StatusTag/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('md 32px — Document Item, SR header'),
      row(h(G.StatusTag, { status: 'completed' }), h(G.StatusTag, { status: 'under-review' }), h(G.StatusTag, { status: 'needs-description' }), h(G.StatusTag, { status: 'missing-info' }), h(G.StatusTag, { status: 'rejected' }), h(G.StatusTag, { status: 'draft' }), h(G.StatusTag, { status: 'info', label: 'Awaiting SGS review' })),
      cap('sm 24px — tables, mobile cards'),
      row(h(G.StatusTag, { status: 'completed', size: 'sm', label: 'Certificate issued' }), h(G.StatusTag, { status: 'missing-info', size: 'sm', label: 'Action required' })),
      cap('compact — small breakpoints; icon only, label kept as aria-label + tooltip'),
      row(h(G.StatusTag, { status: 'completed', compact: true }), h(G.StatusTag, { status: 'under-review', compact: true }), h(G.StatusTag, { status: 'missing-info', compact: true }), h(G.StatusTag, { status: 'rejected', compact: true }))
    ));
}

