// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Table/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      cap('Static table for small, read-only sets inside a card (e.g. General Information, Affected Products). Default 48px rows.'),
      h(G.Table, { caption: 'Accessible groups', columns: [{ key: 'g', header: 'Group name' }, { key: 'f', header: 'Folder(s)' }, { key: 'l', header: 'Level(s)' }, { key: 'u', header: 'Users', align: 'end' }],
        rows: [{ g: 'Compliance team', f: 'Evidence / 2026', l: 'Level 2', u: 8 }, { g: 'Auditors', f: 'Reviews', l: 'Level 1', u: 3 }, { g: 'Finance', f: 'Invoices', l: 'Level 3', u: 5 }] }),
      cap('compact 40px'),
      h(G.Table, { density: 'compact', columns: [{ key: 'p', header: 'Product' }, { key: 'hs', header: 'HS code' }, { key: 'q', header: 'Qty', align: 'end' }], rows: [{ p: 'Face cream 50 ml', hs: '3304.99', q: 1200 }, { p: 'Lip balm', hs: '3304.10', q: 800 }] })
    ));
}

