// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Tabs/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('line (default)'),
      h(G.Tabs, { label: 'Request sections', tabs: [{ id: 'd', label: 'Request Details', content: 'Country of Destination: Saudi Arabia · Service Required: Product Conformity Assessment' }, { id: 'doc', label: 'Documents', badge: 3, content: '3 documents attached.' }, { id: 'tp', label: 'Trade Parties', content: 'Seller, Buyer' }, { id: 'x', label: 'Shipment Details', disabled: true }] }),
      cap('contained — tabs on a card, selected tab joins the panel'),
      h(G.Tabs, { variant: 'contained', label: 'Profile', tabs: [{ id: 'a', label: 'Client Identification', content: 'Legal name, registration number, HQ address.' }, { id: 'b', label: 'Contact Person', content: 'Primary and billing contacts.' }, { id: 'c', label: 'Administrator(s)', content: 'Users who can manage this tenant.' }] })
    ));
}

