// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Tag/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Neutral · required · info — words, not state (for state use StatusTag)'),
      row(h(G.Tag, null, 'ISO/IEC 27001'), h(G.Tag, { tone: 'required' }, 'Required'), h(G.Tag, { tone: 'info' }, 'Optional'))
    ));
}

