// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Textarea/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      h(G.Textarea, { label: 'Document description', required: true, placeholder: 'Describe what this document proves', helpText: 'Up to 500 characters.' }),
      h(G.Textarea, { label: 'Response to finding', rows: 3, error: 'A response is required before you submit.' })
    ));
}

