// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/TextInput/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }
  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Widths S 232 · M 392 (default) · L 552 — fields never stretch with the screen'),
      h(G.TextInput, { label: 'Postal code', size: 's', placeholder: '00100' }),
      h(G.TextInput, { label: 'Reference', placeholder: 'e.g. PO-2026-0042' }),
      h(G.TextInput, { label: 'Company legal name', size: 'l', placeholder: 'SGS Nairobi Limited' }),
      cap('Password (show/hide) · read-only'),
      row(h(G.TextInput, { label: 'Password', type: 'password', required: true, defaultValue: 'secret123' }), h(G.TextInput, { label: 'Tenant', size: 's', readOnly: true, defaultValue: 'SGS-KE-01' }))
    ));
}

