// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/Tooltip/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function row(){ return h.apply(null, ['div', { className: 'gr-demo__row' }].concat([].slice.call(arguments))); }
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo' },
      cap('Shown on hover and keyboard focus, hidden with Esc · dark bubble, 12/20, max 240px'),
      h('div', { style: { paddingTop: 40 } }, row(
        h(G.Tooltip, { label: 'Upload for Actions Required', open: true }, h(G.Button, { variant: 'tertiary', size: 'md' }, 'Always open (demo)')),
        h(G.IconButton, { icon: 'add', label: 'Add another party' }),
        h(G.StatusTag, { status: 'missing-info', compact: true }),
        h(G.Tooltip, { label: 'invoice234657.pdf • Uploaded January 20, 2026 • 2.4 MB', placement: 'bottom' }, h('span', { tabIndex: 0, style: { fontSize: 14, maxWidth: 160, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', display: 'inline-block' } }, 'invoice234657.pdf • Uploaded January 20, 2026'))))
    ));
}

