// @ts-nocheck -- demo code copied verbatim from the DS preview (untyped ES5).
// Generated by scripts/gen-showcase.mjs from design-system/graphite/components/TopBar/preview.html. Do not edit by hand.
'use client';
import * as React from 'react';
import * as G from '@sgs/graphite';
const h = React.createElement;

  
  function cap(t){ return h('div', { className: 'gr-demo__cap' }, t); }

  export default function Preview() {
  return (h('div', { className: 'gr-demo', style: { background: 'var(--background)' } },
      cap('home — Request Applications (orange), Communications, notifications, profile'),
      h(G.TopBar, { variant: 'home', siteName: 'Government & Trade Facilitation', siteSub: 'The Official Exporter Portal', userName: 'Linh Tran', userEmail: 'linh.tran@abc-trading.com', notifications: 3 }),
      cap('home · compact (1178–1279px) — text links become icon buttons'),
      h(G.TopBar, { variant: 'home', compact: true, siteName: 'Government & Trade Facilitation', siteSub: 'The Official Exporter Portal', userName: 'Linh Tran', notifications: 3 }),
      cap('landing'),
      h(G.TopBar, { variant: 'landing', siteName: 'Digital Trust Platform' }),
      cap('login — transparent; inside data-theme="inverse" the wordmark turns white'),
      h('div', { 'data-theme': 'inverse', style: { background: 'var(--background)', borderRadius: 8 } }, h(G.TopBar, { variant: 'login', siteName: 'Digital Trust Platform', siteSub: 'Customer Portal' }))
    ));
}

