// Generated by scripts/gen-showcase.mjs. Do not edit by hand.
import type { ComponentType } from 'react';
import type { IconName } from '@sgs/graphite';

export const iconNames: IconName[] = ["checkmark--filled","time--filled","warning--alt--filled","warning--filled","misuse","circle-dash","information--filled","search","chevron--down","close","arrow--right","add","view","view--off","overflow-menu--vertical","earth","checkmark","arrow--up","arrow--down","arrows--vertical","chevron--left","chevron--right","calendar","upload","document","information","folder","events","box","delivery","notification","user--avatar","edit","launch","trash-can","download","save","arrow--left","send","document--pdf","dashboard","category","folders","document--multiple-01","task","education","catalog","settings","user--multiple","user--access","side-panel--close","side-panel--open"];
import D0 from './demos/Accordion';
import D1 from './demos/AppShell';
import D2 from './demos/AppSidebar';
import D3 from './demos/Avatar';
import D4 from './demos/Breadcrumb';
import D5 from './demos/Button';
import D6 from './demos/Card';
import D7 from './demos/Checkbox';
import D8 from './demos/Combobox';
import D9 from './demos/CommentThread';
import D10 from './demos/DataTable';
import D11 from './demos/DatePicker';
import D12 from './demos/DocumentItem';
import D13 from './demos/Drawer';
import D14 from './demos/EmptyState';
import D15 from './demos/FileUpload';
import D16 from './demos/FormField';
import D17 from './demos/IconButton';
import D18 from './demos/InlineNotification';
import D19 from './demos/LanguageSelector';
import D20 from './demos/Link';
import D21 from './demos/ListPage';
import D22 from './demos/Modal';
import D23 from './demos/MultiSelect';
import D24 from './demos/NotificationBadge';
import D25 from './demos/NotificationCenter';
import D26 from './demos/OverflowMenu';
import D27 from './demos/PageHeader';
import D28 from './demos/Pagination';
import D29 from './demos/Popover';
import D30 from './demos/ProgressBar';
import D31 from './demos/Radio';
import D32 from './demos/ReadinessRing';
import D33 from './demos/RequestDetailPage';
import D34 from './demos/RequirementNavigator';
import D35 from './demos/SearchInput';
import D36 from './demos/SectionNav';
import D37 from './demos/Select';
import D38 from './demos/Separator';
import D39 from './demos/Skeleton';
import D40 from './demos/Snackbar';
import D41 from './demos/StatusTag';
import D42 from './demos/Table';
import D43 from './demos/Tabs';
import D44 from './demos/Tag';
import D45 from './demos/TextInput';
import D46 from './demos/Textarea';
import D47 from './demos/Toggle';
import D48 from './demos/Tooltip';
import D49 from './demos/TopBar';
import D50 from './demos/TreeView';
import D51 from './demos/WizardPage';

export interface DemoEntry { name: string; group: string; height: number; width: number; page: boolean; description: string; Demo: ComponentType }

export const demos: DemoEntry[] = [
  { ...{"name":"Accordion","group":"Containers","height":400,"width":0,"page":false,"description":"Collapsible sections; used for Seller/Buyer cards (\"Edit / Collapse\") and \"Affected Products\" in Document Item."}, Demo: D0 },
  { ...{"name":"AppShell","group":"Page templates","height":900,"width":1440,"page":true,"description":"Shared shell for every screen after sign-in: **TopBar** (`home`) on top, **AppSidebar** on the left, and the **content area** in the middle."}, Demo: D1 },
  { ...{"name":"AppSidebar","group":"Patterns","height":760,"width":0,"page":false,"description":"Primary navigation of the Customer Portal, running down the left side. It has two levels: top-level items, and child items under a group. Which items appear depends on the role."}, Demo: D2 },
  { ...{"name":"Avatar","group":"Navigation","height":140,"width":0,"page":false,"description":"A user's photo or initials; used in the top bar (Profile menu), comments, and the assignee."}, Demo: D3 },
  { ...{"name":"Breadcrumb","group":"Navigation","height":120,"width":0,"page":false,"description":"Shows where the page sits in the navigation tree; parent levels are orange Links, and the current page is medium-weight `text-primary` text that is not clickable."}, Demo: D4 },
  { ...{"name":"Button","group":"Actions","height":360,"width":0,"page":false,"description":"Pill-shaped action button; each screen has **one** `primary` (orange) button for the main action."}, Demo: D5 },
  { ...{"name":"Card","group":"Patterns","height":560,"width":0,"page":false,"description":"The main content block in the middle column of an SR screen: step number, title and description, then the body."}, Demo: D6 },
  { ...{"name":"Checkbox","group":"Selection","height":150,"width":0,"page":false,"description":"An independent or multi-select control; when checked, the fill switches to `brand-orange`."}, Demo: D7 },
  { ...{"name":"Combobox","group":"Forms","height":400,"width":0,"page":false,"description":"A field you type into and pick one value from a long list: company, country, framework."}, Demo: D8 },
  { ...{"name":"CommentThread","group":"Patterns","height":560,"width":0,"page":false,"description":"The conversation between the customer and SGS (the Messages pane in the right column of an SR screen, review comments, clarification)."}, Demo: D9 },
  { ...{"name":"DataTable","group":"Data","height":1160,"width":0,"page":false,"description":"A full data table: search, sort, row selection with a bulk-action bar, a per-row action menu, pagination, and loading, empty, and error states. On a narrow screen the table becomes a card list (the mobile pattern in the UI Guidelines)."}, Demo: D10 },
  { ...{"name":"DatePicker","group":"Forms","height":470,"width":0,"page":false,"description":"Pick a date from a popover calendar; shown as **DD MMM YYYY** (12 Oct 2026) so day/month order is not confused across locales."}, Demo: D11 },
  { ...{"name":"DocumentItem","group":"Patterns","height":640,"width":0,"page":false,"description":"One document in an SR, following the \"Document Item UI Guidelines\" spec, made of 5 regions."}, Demo: D12 },
  { ...{"name":"Drawer","group":"Overlay","height":460,"width":0,"page":false,"description":"A panel that slides in from the right for detail or a quick edit without leaving the page: evidence detail, review comment, history."}, Demo: D13 },
  { ...{"name":"EmptyState","group":"Feedback","height":300,"width":0,"page":false,"description":"The content shown when there is no data yet: what this is, why it is empty, and the next step."}, Demo: D14 },
  { ...{"name":"FileUpload","group":"Forms","height":520,"width":0,"page":false,"description":"A drag-and-drop area with a file list and a status for each file; the centre of Evidence Management."}, Demo: D15 },
  { ...{"name":"FormField","group":"Forms","height":420,"width":0,"page":false,"description":"The shared frame for every input control: a label, a filled field (with an underline), and **one** message underneath."}, Demo: D16 },
  { ...{"name":"IconButton","group":"Actions","height":200,"width":0,"page":false,"description":"A round button that contains only an icon; a `label` is required (used as the `aria-label` and tooltip, per UI Guidelines §8)."}, Demo: D17 },
  { ...{"name":"InlineNotification","group":"Feedback","height":460,"width":0,"page":false,"description":"An in-page notice that does not dismiss itself, for information the user needs while they work: \"Required Information\", \"Action required\", \"Need help?\"."}, Demo: D18 },
  { ...{"name":"LanguageSelector","group":"Navigation","height":260,"width":0,"page":false,"description":"Chooses the interface language; currently **English** and **繁體中文** (Traditional Chinese), placed at the right of the top bar."}, Demo: D19 },
  { ...{"name":"Link","group":"Actions","height":220,"width":0,"page":false,"description":"Orange text link in `link-primary` (#CA4300); weight is Regular or Semibold only."}, Demo: D20 },
  { ...{"name":"ListPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"A page that lists records: Service Requests, Gap Analysis, Workspaces, Documents, Users, Audit Logs."}, Demo: D21 },
  { ...{"name":"Modal","group":"Overlay","height":440,"width":0,"page":false,"description":"A blocking dialog for a confirmation or a short input; while it is open, **the whole background is dimmed** with `overlay` (UI Guidelines §9)."}, Demo: D22 },
  { ...{"name":"MultiSelect","group":"Forms","height":380,"width":0,"page":false,"description":"Select several values (Role/s, Collector/s, Frameworks); selected values appear as chips with a remove control."}, Demo: D23 },
  { ...{"name":"NotificationBadge","group":"Navigation","height":140,"width":0,"page":false,"description":"A count or a red dot on an icon (the Notifications bell, Communications) in the top bar."}, Demo: D24 },
  { ...{"name":"NotificationCenter","group":"Feedback","height":760,"width":0,"page":false,"description":"A notification inbox **shared** by the Customer Portal and SGS Operations, opened from the **bell on the TopBar**. There is no separate page. It covers UC-NTF-002 (View Notification Inbox and History); the content is produced by UC-NTF-001 (the system generates notifications)."}, Demo: D25 },
  { ...{"name":"OverflowMenu","group":"Actions","height":260,"width":0,"page":false,"description":"A vertical three-dot button that opens a list of actions; per the guideline, when there are **more than 3 actions** they all go here, and at the small breakpoint every action goes here."}, Demo: D26 },
  { ...{"name":"PageHeader","group":"Patterns","height":260,"width":0,"page":false,"description":"The page heading for working screens (SR creation, edit, review): back button, title and description, status, autosave, and actions."}, Demo: D27 },
  { ...{"name":"Pagination","group":"Data","height":200,"width":0,"page":false,"description":"The paging bar at the foot of a table, following the SR mockup: \"Items per page\" → \"1–10 of 100 items\" on the left; a page field → \"of 10 pages\" → previous/next buttons on the right."}, Demo: D28 },
  { ...{"name":"Popover","group":"Overlay","height":260,"width":0,"page":false,"description":"A floating panel anchored to a trigger, for filters, a small form, or secondary information; it does not dim the background the way a Modal does."}, Demo: D29 },
  { ...{"name":"ProgressBar","group":"Feedback","height":280,"width":0,"page":false,"description":"A progress bar for uploads, readiness, and processing steps; always shown with a percentage or supporting text."}, Demo: D30 },
  { ...{"name":"Radio","group":"Selection","height":200,"width":0,"page":false,"description":"Pick exactly one of 2–5 options that stay visible; for more than that, use Select."}, Demo: D31 },
  { ...{"name":"ReadinessRing","group":"Feedback","height":200,"width":0,"page":false,"description":"A ring that shows readiness: the share of requirements in a framework that have accepted evidence."}, Demo: D32 },
  { ...{"name":"RequestDetailPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"The detail page for one request (SR, Gap Analysis, Implementation Support). It follows the **3-column** layout in the UI Guidelines, section *Responsiveness · SR creation*."}, Demo: D33 },
  { ...{"name":"RequirementNavigator","group":"Data","height":720,"width":0,"page":false,"description":"The requirement list of a framework, grouped by clause or control group; **each row is its own block**. Used in the left column of requirement working screens: the consultant assesses the gap, the customer uploads evidence in the workspace, the reviewer decides."}, Demo: D34 },
  { ...{"name":"SearchInput","group":"Forms","height":200,"width":0,"page":false,"description":"A search field with a magnifying-glass icon; the label is visually hidden by default but still read by a screen reader."}, Demo: D35 },
  { ...{"name":"SectionNav","group":"Navigation","height":340,"width":0,"page":false,"description":"Vertical navigation between sections of a long form (the left column of SR creation), with a completion state for each section."}, Demo: D36 },
  { ...{"name":"Select","group":"Forms","height":340,"width":0,"page":false,"description":"A dropdown that selects one value, following the **Radix Select** anatomy: the trigger sits inside FormField, and the list opens directly below, the same width as the field."}, Demo: D37 },
  { ...{"name":"Separator","group":"Containers","height":160,"width":0,"page":false,"description":"A 1px divider in `border-subtle-00`, horizontal or vertical."}, Demo: D38 },
  { ...{"name":"Skeleton","group":"Feedback","height":200,"width":0,"page":false,"description":"A placeholder block while content is loading, so the layout does not jump."}, Demo: D39 },
  { ...{"name":"Snackbar","group":"Feedback","height":240,"width":0,"page":false,"description":"Feedback after an action (saved, submitted); per the guideline it is a Material snackbar, **centred at the bottom of the screen, temporary, and auto-dismissing**."}, Demo: D40 },
  { ...{"name":"StatusTag","group":"Status","height":320,"width":0,"page":false,"description":"The status of a document, SR, or evidence, always icon plus text; the icon and colour come from the Status icons set."}, Demo: D41 },
  { ...{"name":"Table","group":"Data","height":330,"width":0,"page":false,"description":"A static, read-only table for a small data set inside a card: General Information, Accessible Group(s), Affected Products. For sort, filter, row selection, or pagination, use **DataTable**."}, Demo: D42 },
  { ...{"name":"Tabs","group":"Navigation","height":340,"width":0,"page":false,"description":"Switches between peer groups of content in the same context."}, Demo: D43 },
  { ...{"name":"Tag","group":"Status","height":150,"width":0,"page":false,"description":"A short one- or two-word label for classification, with no status meaning; to show status, use StatusTag."}, Demo: D44 },
  { ...{"name":"TextInput","group":"Forms","height":400,"width":0,"page":false,"description":"A single-line input built on FormField; the value is shown at 16/24 Regular (Roboto 16, about 9px per character)."}, Demo: D45 },
  { ...{"name":"Textarea","group":"Forms","height":300,"width":0,"page":false,"description":"A multi-line input for a document description, a finding response, or a note; default size `l`, 4 rows, resizable vertically."}, Demo: D46 },
  { ...{"name":"Toggle","group":"Selection","height":150,"width":0,"page":false,"description":"An on/off switch that takes effect immediately, with no Save; when on, the track switches to `brand-orange`."}, Demo: D47 },
  { ...{"name":"Tooltip","group":"Feedback","height":200,"width":0,"page":false,"description":"A short label shown on hover or keyboard focus; required for every icon-only control and every icon-only status (UI Guidelines §8)."}, Demo: D48 },
  { ...{"name":"TopBar","group":"Patterns","height":420,"width":0,"page":false,"description":"The bar across the top of the application. There are 3 kinds, per UI Guidelines §11."}, Demo: D49 },
  { ...{"name":"TreeView","group":"Data","height":360,"width":0,"page":false,"description":"A hierarchy, for example Framework → Clause → Requirement (the REQUIREMENT table has `parent_id`), used to browse requirements and attach evidence."}, Demo: D50 },
  { ...{"name":"WizardPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"A multi-step create flow: Gap Analysis (5 steps), Service Request, create Scope."}, Demo: D51 },
];
