// Generated by scripts/gen-showcase.mjs. Do not edit by hand.
import type { ComponentType } from 'react';
import type { IconName } from '@sgs/graphite';

export const iconNames: IconName[] = ["checkmark--filled","time--filled","warning--alt--filled","warning--filled","misuse","circle-dash","information--filled","search","chevron--down","close","arrow--right","add","view","view--off","overflow-menu--vertical","earth","checkmark","arrow--up","arrow--down","arrows--vertical","chevron--left","chevron--right","calendar","upload","document","information","folder","events","box","delivery","notification","user--avatar","edit","launch","trash-can","download","save","arrow--left","send","document--pdf","dashboard","category","folders","document--multiple-01","task","education","catalog","settings","user--multiple","user--access","side-panel--close","side-panel--open"];
import D0 from './demos/Accordion';
import D1 from './demos/AppShell';
import D2 from './demos/AppSidebar';
import D3 from './demos/Avatar';
import D4 from './demos/Breadcrumb';
import D5 from './demos/Button';
import D6 from './demos/Card';
import D7 from './demos/Checkbox';
import D8 from './demos/Combobox';
import D9 from './demos/CommentThread';
import D10 from './demos/DataTable';
import D11 from './demos/DatePicker';
import D12 from './demos/DocumentItem';
import D13 from './demos/Drawer';
import D14 from './demos/EmptyState';
import D15 from './demos/FileUpload';
import D16 from './demos/FormField';
import D17 from './demos/IconButton';
import D18 from './demos/InlineNotification';
import D19 from './demos/LanguageSelector';
import D20 from './demos/Link';
import D21 from './demos/ListPage';
import D22 from './demos/Modal';
import D23 from './demos/MultiSelect';
import D24 from './demos/NotificationBadge';
import D25 from './demos/NotificationCenter';
import D26 from './demos/OverflowMenu';
import D27 from './demos/PageHeader';
import D28 from './demos/Pagination';
import D29 from './demos/Popover';
import D30 from './demos/ProgressBar';
import D31 from './demos/Radio';
import D32 from './demos/ReadinessRing';
import D33 from './demos/RequestDetailPage';
import D34 from './demos/RequirementNavigator';
import D35 from './demos/SearchInput';
import D36 from './demos/SectionNav';
import D37 from './demos/Select';
import D38 from './demos/Separator';
import D39 from './demos/Skeleton';
import D40 from './demos/Snackbar';
import D41 from './demos/StatusTag';
import D42 from './demos/Table';
import D43 from './demos/Tabs';
import D44 from './demos/Tag';
import D45 from './demos/TextInput';
import D46 from './demos/Textarea';
import D47 from './demos/Toggle';
import D48 from './demos/Tooltip';
import D49 from './demos/TopBar';
import D50 from './demos/TreeView';
import D51 from './demos/WizardPage';

export interface DemoEntry { name: string; group: string; height: number; width: number; page: boolean; description: string; Demo: ComponentType }

export const demos: DemoEntry[] = [
  { ...{"name":"Accordion","group":"Containers","height":400,"width":0,"page":false,"description":"Các khối thu gọn/mở rộng; dùng cho card Seller/Buyer (\"Edit / Collapse\") và \"Affected Products\" trong Document Item."}, Demo: D0 },
  { ...{"name":"AppShell","group":"Page templates","height":900,"width":1440,"page":true,"description":"Khung vỏ dùng chung cho mọi màn sau khi đăng nhập: **TopBar** (`home`) ở trên, **AppSidebar** bên trái, **vùng nội dung** ở giữa."}, Demo: D1 },
  { ...{"name":"AppSidebar","group":"Patterns","height":760,"width":0,"page":false,"description":"Điều hướng chính của Customer Portal, nằm dọc bên trái. Có 2 cấp: mục chính, và mục con dưới một nhóm. Các mục hiện ra khác nhau tuỳ theo role."}, Demo: D2 },
  { ...{"name":"Avatar","group":"Navigation","height":140,"width":0,"page":false,"description":"Ảnh đại diện hoặc chữ viết tắt của người dùng; dùng ở top bar (menu Profile), comment, người phụ trách."}, Demo: D3 },
  { ...{"name":"Breadcrumb","group":"Navigation","height":120,"width":0,"page":false,"description":"Cho biết vị trí trang trong cây điều hướng; các cấp trên là Link cam, trang hiện tại là chữ `text-primary` đậm vừa và không bấm được."}, Demo: D4 },
  { ...{"name":"Button","group":"Actions","height":360,"width":0,"page":false,"description":"Nút hành động dạng pill; mỗi màn chỉ có **một** nút `primary` (cam) cho hành động chính."}, Demo: D5 },
  { ...{"name":"Card","group":"Patterns","height":560,"width":0,"page":false,"description":"Khối nội dung chính ở cột giữa màn SR, gồm số thứ tự bước, tiêu đề và mô tả, rồi nội dung."}, Demo: D6 },
  { ...{"name":"Checkbox","group":"Selection","height":150,"width":0,"page":false,"description":"Ô chọn độc lập hoặc chọn nhiều; khi được chọn, nền chuyển sang `brand-orange`."}, Demo: D7 },
  { ...{"name":"Combobox","group":"Forms","height":400,"width":0,"page":false,"description":"Ô vừa gõ vừa chọn một giá trị trong danh sách dài: công ty, quốc gia, framework."}, Demo: D8 },
  { ...{"name":"CommentThread","group":"Patterns","height":560,"width":0,"page":false,"description":"Luồng trao đổi giữa khách hàng và SGS (phần Messages ở cột phải màn SR, review comment, clarification)."}, Demo: D9 },
  { ...{"name":"DataTable","group":"Data","height":1160,"width":0,"page":false,"description":"Bảng dữ liệu đầy đủ: tìm kiếm, sort, chọn dòng kèm thanh bulk action, menu action trên từng dòng, phân trang, và các trạng thái loading, empty, error. Trên màn hẹp, bảng tự chuyển thành danh sách card (pattern mobile trong UI Guidelines)."}, Demo: D10 },
  { ...{"name":"DatePicker","group":"Forms","height":470,"width":0,"page":false,"description":"Chọn một ngày qua lịch bật ra; hiển thị dạng **DD MMM YYYY** (12 Oct 2026) để tránh nhầm giữa định dạng ngày/tháng của các nước."}, Demo: D11 },
  { ...{"name":"DocumentItem","group":"Patterns","height":640,"width":0,"page":false,"description":"Một tài liệu trong SR, theo đúng spec \"Document Item UI Guidelines\", gồm 5 vùng."}, Demo: D12 },
  { ...{"name":"Drawer","group":"Overlay","height":460,"width":0,"page":false,"description":"Panel trượt vào từ bên phải, dùng cho chi tiết hoặc sửa nhanh mà không rời trang: chi tiết evidence, review comment, lịch sử."}, Demo: D13 },
  { ...{"name":"EmptyState","group":"Feedback","height":300,"width":0,"page":false,"description":"Nội dung khi chưa có dữ liệu: nói rõ đây là gì, vì sao trống và bước tiếp theo."}, Demo: D14 },
  { ...{"name":"FileUpload","group":"Forms","height":520,"width":0,"page":false,"description":"Vùng kéo-thả file kèm danh sách file và trạng thái từng file; là trung tâm của Evidence Management."}, Demo: D15 },
  { ...{"name":"FormField","group":"Forms","height":420,"width":0,"page":false,"description":"Khung chung cho mọi control nhập liệu: label, vùng field kiểu filled (có underline), và **một** thông điệp bên dưới."}, Demo: D16 },
  { ...{"name":"IconButton","group":"Actions","height":200,"width":0,"page":false,"description":"Nút tròn chỉ có icon; bắt buộc có `label` (dùng làm `aria-label` và tooltip, theo UI Guidelines §8)."}, Demo: D17 },
  { ...{"name":"InlineNotification","group":"Feedback","height":460,"width":0,"page":false,"description":"Khung thông báo nằm trong trang, không tự ẩn, dùng cho thông tin người dùng cần thấy khi đang làm việc: \"Required Information\", \"Action required\", \"Need help?\"."}, Demo: D18 },
  { ...{"name":"LanguageSelector","group":"Navigation","height":260,"width":0,"page":false,"description":"Chọn ngôn ngữ giao diện; hiện có 2 lựa chọn là **English** và **繁體中文** (Traditional Chinese), đặt ở góc phải top bar."}, Demo: D19 },
  { ...{"name":"Link","group":"Actions","height":220,"width":0,"page":false,"description":"Liên kết văn bản màu cam `link-primary` (#CA4300), weight chỉ Regular hoặc Semibold."}, Demo: D20 },
  { ...{"name":"ListPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"Trang liệt kê bản ghi: Service Requests, Gap Analysis, Workspaces, Documents, Users, Audit Logs."}, Demo: D21 },
  { ...{"name":"Modal","group":"Overlay","height":440,"width":0,"page":false,"description":"Hộp thoại chặn tương tác để xác nhận hoặc nhập một việc ngắn; khi mở, **toàn bộ nền bị làm tối** bằng `overlay` (UI Guidelines §9)."}, Demo: D22 },
  { ...{"name":"MultiSelect","group":"Forms","height":380,"width":0,"page":false,"description":"Chọn nhiều giá trị (Role/s, Collector/s, Frameworks); giá trị đã chọn hiện thành chip có nút xoá."}, Demo: D23 },
  { ...{"name":"NotificationBadge","group":"Navigation","height":140,"width":0,"page":false,"description":"Số đếm hoặc chấm đỏ đặt trên icon (chuông Notifications, Communications) ở top bar."}, Demo: D24 },
  { ...{"name":"NotificationCenter","group":"Feedback","height":760,"width":0,"page":false,"description":"Hộp thông báo **dùng chung** cho cả Customer Portal và SGS Operations, mở ra từ **chuông trên TopBar**. Không có trang riêng. Đáp ứng UC-NTF-002 (View Notification Inbox and History); nội dung do UC-NTF-001 (hệ thống sinh thông báo) tạo ra."}, Demo: D25 },
  { ...{"name":"OverflowMenu","group":"Actions","height":260,"width":0,"page":false,"description":"Nút ba chấm dọc mở danh sách action; theo guideline, khi có **nhiều hơn 3 action** thì gom hết vào đây, và ở breakpoint nhỏ mọi action đều vào đây."}, Demo: D26 },
  { ...{"name":"PageHeader","group":"Patterns","height":260,"width":0,"page":false,"description":"Tiêu đề trang của các màn làm việc (SR creation, edit, review): nút quay lại, tiêu đề và mô tả, status, autosave, và các action."}, Demo: D27 },
  { ...{"name":"Pagination","group":"Data","height":200,"width":0,"page":false,"description":"Thanh phân trang ở chân bảng, theo mẫu trong mockup SR: \"Items per page\" → \"1–10 of 100 items\" ở bên trái; ô chọn trang → \"of 10 pages\" → nút trước/sau ở bên phải."}, Demo: D28 },
  { ...{"name":"Popover","group":"Overlay","height":260,"width":0,"page":false,"description":"Khung nổi gắn vào một trigger, dùng cho bộ lọc, form nhỏ hoặc thông tin phụ; không làm tối nền như Modal."}, Demo: D29 },
  { ...{"name":"ProgressBar","group":"Feedback","height":280,"width":0,"page":false,"description":"Thanh tiến độ cho upload, readiness và các bước xử lý; luôn hiện kèm số % hoặc nội dung."}, Demo: D30 },
  { ...{"name":"Radio","group":"Selection","height":200,"width":0,"page":false,"description":"Chọn đúng một trong nhóm 2–5 lựa chọn luôn hiển thị; nhiều hơn thế thì dùng Select."}, Demo: D31 },
  { ...{"name":"ReadinessRing","group":"Feedback","height":200,"width":0,"page":false,"description":"Vòng tròn thể hiện readiness: tỷ lệ requirement đã có evidence được chấp nhận trong một framework."}, Demo: D32 },
  { ...{"name":"RequestDetailPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"Trang chi tiết một request (SR, Gap Analysis, Implementation Support). Theo bố cục **3 cột** của UI Guidelines, phần *Responsiveness · SR creation*."}, Demo: D33 },
  { ...{"name":"RequirementNavigator","group":"Data","height":720,"width":0,"page":false,"description":"Danh sách requirement của một framework, chia theo clause hoặc nhóm control; **mỗi dòng là một khối riêng**. Dùng ở cột trái của các màn làm việc trên requirement: consultant đánh giá gap, khách hàng upload evidence trong workspace, reviewer duyệt."}, Demo: D34 },
  { ...{"name":"SearchInput","group":"Forms","height":200,"width":0,"page":false,"description":"Ô tìm kiếm có icon kính lúp; label mặc định được ẩn khỏi mắt nhưng vẫn được screen reader đọc."}, Demo: D35 },
  { ...{"name":"SectionNav","group":"Navigation","height":340,"width":0,"page":false,"description":"Điều hướng dọc giữa các section của một form dài (cột trái màn SR creation), kèm trạng thái hoàn thành của từng section."}, Demo: D36 },
  { ...{"name":"Select","group":"Forms","height":340,"width":0,"page":false,"description":"Dropdown chọn một giá trị, theo anatomy của **Radix Select**: nút trigger nằm trong FormField, danh sách mở ra ngay bên dưới, rộng bằng đúng field."}, Demo: D37 },
  { ...{"name":"Separator","group":"Containers","height":160,"width":0,"page":false,"description":"Đường kẻ ngăn 1px `border-subtle-00`, ngang hoặc dọc."}, Demo: D38 },
  { ...{"name":"Skeleton","group":"Feedback","height":200,"width":0,"page":false,"description":"Khối giữ chỗ khi đang tải; giúp màn hình không bị nhảy bố cục."}, Demo: D39 },
  { ...{"name":"Snackbar","group":"Feedback","height":240,"width":0,"page":false,"description":"Phản hồi sau một thao tác (đã lưu, đã gửi); theo guideline là Material snackbar, **giữa phía dưới màn hình, tạm thời, tự ẩn**."}, Demo: D40 },
  { ...{"name":"StatusTag","group":"Status","height":320,"width":0,"page":false,"description":"Trạng thái của tài liệu, SR hay evidence, luôn gồm icon và chữ; icon và màu lấy theo bộ Status icons."}, Demo: D41 },
  { ...{"name":"Table","group":"Data","height":330,"width":0,"page":false,"description":"Bảng tĩnh, chỉ để đọc, dùng cho tập dữ liệu nhỏ nằm trong card: General Information, Accessible Group(s), Affected Products. Cần sort, lọc, chọn dòng hay phân trang thì dùng **DataTable**."}, Demo: D42 },
  { ...{"name":"Tabs","group":"Navigation","height":340,"width":0,"page":false,"description":"Chuyển giữa các nhóm nội dung ngang hàng trong cùng một ngữ cảnh."}, Demo: D43 },
  { ...{"name":"Tag","group":"Status","height":150,"width":0,"page":false,"description":"Nhãn ngắn một đến hai từ để phân loại, không mang trạng thái; muốn thể hiện trạng thái thì dùng StatusTag."}, Demo: D44 },
  { ...{"name":"TextInput","group":"Forms","height":400,"width":0,"page":false,"description":"Ô nhập một dòng, dựng trên FormField; giá trị hiển thị ở 16/24 Regular (Roboto 16, khoảng 9px mỗi ký tự)."}, Demo: D45 },
  { ...{"name":"Textarea","group":"Forms","height":300,"width":0,"page":false,"description":"Ô nhập nhiều dòng cho mô tả tài liệu, phản hồi finding, ghi chú; mặc định cỡ `l`, 4 dòng, kéo giãn theo chiều dọc."}, Demo: D46 },
  { ...{"name":"Toggle","group":"Selection","height":150,"width":0,"page":false,"description":"Công tắc bật/tắt có hiệu lực ngay, không cần bấm Save; khi bật, track chuyển sang `brand-orange`."}, Demo: D47 },
  { ...{"name":"Tooltip","group":"Feedback","height":200,"width":0,"page":false,"description":"Nhãn ngắn hiện khi hover hoặc focus bằng bàn phím; bắt buộc cho mọi control chỉ có icon và mọi status chỉ có icon (UI Guidelines §8)."}, Demo: D48 },
  { ...{"name":"TopBar","group":"Patterns","height":420,"width":0,"page":false,"description":"Thanh trên cùng của ứng dụng. Có 3 loại theo UI Guidelines §11."}, Demo: D49 },
  { ...{"name":"TreeView","group":"Data","height":360,"width":0,"page":false,"description":"Cây phân cấp, ví dụ Framework → Clause → Requirement (bảng REQUIREMENT có `parent_id`), dùng để duyệt requirement và gắn evidence."}, Demo: D50 },
  { ...{"name":"WizardPage","group":"Page templates","height":900,"width":1440,"page":true,"description":"Luồng tạo mới gồm nhiều bước: Gap Analysis (5 bước), Service Request, tạo Scope."}, Demo: D51 },
];
