// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
// Internal only (not referenced by types/index.d.ts): the reference bundle calls focus() on
// elements returned by querySelectorAll / document.activeElement.
interface Element { focus(options?: FocusOptions): void }
