// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
// The ported implementation is untyped ES5, so React is exposed loosely here.
// The public API is typed strictly by types/index.d.ts (what consumers see).
import * as ReactNS from 'react';
export const React: any = ReactNS;
export const h: (type: any, props?: any, ...children: any[]) => ReactNS.ReactElement = ReactNS.createElement as any;
export const useState: (initial?: any) => [any, (next: any) => void] = ReactNS.useState as any;
export const useEffect: (effect: () => any, deps?: any[]) => void = ReactNS.useEffect as any;
export const useRef: (initial?: any) => { current: any } = ReactNS.useRef as any;
export const useId: () => string = ReactNS.useId;
export const useCallback: (fn: any, deps: any[]) => any = ReactNS.useCallback as any;
