// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.

export function cx(..._args: any[]){var o=[];for(var i=0;i<arguments.length;i++){if(arguments[i])o.push(arguments[i]);}return o.join(' ');}
export function omit(p,keys){var o={};for(var k in p){if(keys.indexOf(k)<0)o[k]=p[k];}return o;}
