'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useId } from '../runtime';
import type { AccordionProps } from '../../types/index';
import { Icon } from './Icon';
import { cx } from '../utils';

export function Accordion(p: AccordionProps){var items=p.items||[];var auto=useId();var init={};items.forEach(function(it){if(it.defaultOpen)init[it.id]=true;});var s=useState(init),open=s[0],setOpen=s[1];
 function toggle(id){var n=p.allowMultiple===false?{}:Object.assign({},open);n[id]=!open[id];setOpen(n);}
 return h('div',{className:cx('gr-acc',p.className)},items.map(function(it){var o=!!open[it.id];var hid=auto+'-h-'+it.id,pid=auto+'-p-'+it.id;
  return h('div',{key:it.id,className:cx('gr-acc__item',o&&'is-open')},
   h('h3',{className:'gr-acc__heading'},h('button',{type:'button',id:hid,className:'gr-acc__trigger','aria-expanded':o,'aria-controls':pid,onClick:function(){toggle(it.id);}},
    h('span',{className:'gr-acc__title'},it.title,it.meta?h('span',{className:'gr-acc__meta'},it.meta):null),
    h('span',{className:'gr-acc__action'},p.showActionLabel===false?null:h('span',null,o?(p.collapseLabel||'Collapse'):(p.expandLabel||'Expand')),h(Icon,{name:'chevron--down',size:20,className:'gr-acc__chev'})))),
   o?h('div',{id:pid,role:'region','aria-labelledby':hid,className:'gr-acc__panel'},it.content):null);}));}
