'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { React, h, useState } from '../runtime';
import type { AppSidebarProps } from '../../types/index';
import { Icon } from './Icon';
import { IconButton } from './IconButton';
import { Popover } from './Popover';
import { Separator } from './Separator';
import { Tooltip } from './Tooltip';
import { cx } from '../utils';
import { tr } from '../tr';

export function sideContains(it,id){return it.id===id||(it.children||[]).some(function(c){return c.id===id;});}
export function AppSidebar(p: AppSidebarProps){var sections=p.sections||[{items:p.items||[]}];var sa=useState(p.defaultActive||null),a=sa[0],setA=sa[1];var act=p.active!==undefined?p.active:a;
 var sc=useState(!!p.defaultCollapsed),c=sc[0],setC=sc[1];var collapsed=p.collapsed!==undefined?p.collapsed:c;
 var init={};sections.forEach(function(s){(s.items||[]).forEach(function(it){if(it.children&&(it.defaultOpen||sideContains(it,act)))init[it.id]=true;});});var so=useState(init),open=so[0],setOpen=so[1];
 function go(it,e){if(!it.href&&e)e.preventDefault();if(p.active===undefined)setA(it.id);if(p.onSelect)p.onSelect(it.id,it);}
 function toggleCollapse(){var n=!collapsed;if(p.collapsed===undefined)setC(n);if(p.onCollapsedChange)p.onCollapsedChange(n);}
 function badge(it){return it.badge!=null?h('span',{className:cx('gr-side__badge',it.badgeTone==='attention'&&'gr-side__badge--attn')},it.badge,h('span',{className:'gr-sr'},' '+(tr(it.badgeLabel||'items')))):null;}
 function leaf(it,child){var cur=it.id===act;
  var link=h('a',{href:it.href||'#',className:cx('gr-side__item',child&&'gr-side__item--child',cur&&'is-current'),'aria-current':cur?'page':undefined,onClick:function(e){go(it,e);}},
   !child&&it.icon?h(Icon,{name:it.icon,size:20,className:'gr-side__icon'}):null,
   h('span',{className:'gr-side__label'},tr(it.label)),badge(it));
  return collapsed&&!child?h(Tooltip,{label:tr(it.label)},link):link;}
 function group(it){var isOpen=!!open[it.id];var inside=sideContains(it,act);var gid='side-'+it.id;
  if(collapsed){return h(Popover,{label:tr(it.label),title:tr(it.label),width:240,trigger:h('button',{type:'button',className:cx('gr-side__item',inside&&'is-current'),'aria-label':tr(it.label)},h(Icon,{name:it.icon,size:20,className:'gr-side__icon'}),it.badge!=null?h('span',{className:'gr-side__dot','aria-hidden':true}):null)},
    h('ul',{className:'gr-side__flyout'},it.children.map(function(ch,i){return ch.type==='label'?h('li',{key:'l'+i,className:'gr-side__glabel'},tr(ch.label)):h('li',{key:ch.id},leaf(ch,true));})));}
  return h(React.Fragment,null,
   h('button',{type:'button',className:cx('gr-side__item',inside&&!isOpen&&'is-current',inside&&'is-within'),'aria-expanded':isOpen,'aria-controls':gid,onClick:function(){var n=Object.assign({},open);n[it.id]=!isOpen;setOpen(n);}},
    h(Icon,{name:it.icon,size:20,className:'gr-side__icon'}),h('span',{className:'gr-side__label'},tr(it.label)),badge(it),h(Icon,{name:'chevron--down',size:16,className:cx('gr-side__chev',isOpen&&'is-open')})),
   isOpen?h('ul',{id:gid,className:'gr-side__sub'},it.children.map(function(ch,i){return ch.type==='label'?h('li',{key:'l'+i,className:'gr-side__glabel gr-side__glabel--sub','aria-hidden':false},tr(ch.label)):h('li',{key:ch.id},leaf(ch,true));})):null);}
 return h('nav',{'aria-label':tr(p.label||'Main'),'data-theme':p.tone==='dark'?'inverse':undefined,className:cx('gr-side',collapsed&&'gr-side--collapsed',p.tone==='dark'&&'gr-side--dark',p.className)},
  p.header?h('div',{className:'gr-side__header'},p.header):null,
  h('div',{className:'gr-side__scroll'},sections.map(function(s,si){return h('div',{key:si,className:'gr-side__section'},
   s.label?(collapsed?h(Separator,{spacing:8,decorative:true}):h('div',{className:'gr-side__slabel',id:'side-s'+si},tr(s.label))):null,
   h('ul',{className:'gr-side__list','aria-labelledby':s.label&&!collapsed?'side-s'+si:undefined},(s.items||[]).map(function(it){return h('li',{key:it.id},it.children?group(it):leaf(it,false));})));})),
  p.collapsible===false?null:h('div',{className:'gr-side__foot'},h(IconButton,{icon:collapsed?'side-panel--open':'side-panel--close',label:tr(collapsed?'Expand sidebar':'Collapse sidebar'),size:'md',tooltipPlacement:'top',onClick:toggleCollapse})));}
