'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { AvatarProps } from '../../types/index';
import { Icon } from './Icon';
import { cx } from '../utils';

export function Avatar(p: AvatarProps){var n=(p.name||'').trim().split(/\s+/);var ini=((n[0]||'')[0]||'')+(n.length>1?(n[n.length-1][0]||''):'');
 return h('span',{className:cx('gr-avatar','gr-avatar--'+(p.size||'md'),p.className),role:'img','aria-label':p.name||'User'},p.src?h('img',{src:p.src,alt:''}):ini.toUpperCase()||h(Icon,{name:'user--avatar',size:20}));}
