'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useEffect, useRef, useId } from '../runtime';
import { cx, omit } from '../utils';

export function Choice(type,cls){return function(p){var auto=useId();var id=p.id||auto;var ref=useRef(null);
 useEffect(function(){if(ref.current)ref.current.indeterminate=!!p.indeterminate;},[p.indeterminate]);
 return h('label',{htmlFor:id,className:cx('gr-choice',p.disabled&&'is-disabled',p.className)},
  h('input',Object.assign({},omit(p,['label','className','indeterminate']),{id:id,ref:ref,type:type==='switch'?'checkbox':type,role:type==='switch'?'switch':undefined,className:cls})),
  p.label?h('span',{className:'gr-choice__label'},p.label):null);};}
export var Checkbox=Choice('checkbox','gr-check'),Radio=Choice('radio','gr-radio'),Toggle=Choice('switch','gr-toggle');
