'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useRef } from '../runtime';
import type { CommentThreadProps } from '../../types/index';
import { Avatar } from './Avatar';
import { Button } from './Button';
import { EmptyState } from './EmptyState';
import { Tag } from './Tag';
import { Textarea } from './Textarea';
import { cx } from '../utils';

export function CommentThread(p: CommentThreadProps){var ms=useState(p.messages||[]),msgs=ms[0],setMsgs=ms[1];var dv=useState(''),draft=dv[0],setDraft=dv[1];var list=useRef(null);
 function send(){var t=draft.trim();if(!t)return;var m={id:'m'+Date.now(),author:p.currentUser||'You',role:p.currentRole||'customer',time:'Just now',body:t};setMsgs(msgs.concat([m]));setDraft('');if(p.onSend)p.onSend(t);setTimeout(function(){if(list.current)list.current.scrollTop=list.current.scrollHeight;},0);}
 return h('section',{className:cx('gr-thread',p.className),'aria-label':p.title||'Messages'},
  p.title?h('div',{className:'gr-thread__head'},h('h2',{className:'gr-thread__title'},p.title),p.count!=null?h('span',{className:'gr-tabs__badge'},p.count):null):null,
  h('div',{ref:list,className:'gr-thread__list',style:p.maxHeight?{maxHeight:p.maxHeight}:undefined,role:'log','aria-live':'polite'},
   msgs.length?msgs.map(function(m){return h('article',{key:m.id,className:cx('gr-msg','gr-msg--'+(m.role||'customer'),m.internal&&'gr-msg--internal')},
     h('div',{className:'gr-msg__head'},h(Avatar,{name:m.author,size:'sm'}),h('span',{className:'gr-msg__author'},m.author),m.role==='sgs'?h(Tag,{tone:'info'},m.roleLabel||'SGS'):null,m.internal?h(Tag,{tone:'required'},'Internal note'):null,h('time',{className:'gr-msg__time'},m.time)),
     h('div',{className:'gr-msg__body'},m.body));}):h(EmptyState,{size:'sm',title:p.emptyTitle||'No messages yet',body:p.emptyBody||'Messages with your SGS reviewer appear here.'})),
  p.readOnly?null:h('div',{className:'gr-thread__composer'},
   h(Textarea,{label:p.composerLabel||'Write a message',hideLabel:true,rows:2,width:'100%',value:draft,placeholder:p.placeholder||'Write a message…',onChange:function(e){setDraft(e.target.value);},onKeyDown:function(e){if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();send();}}}),
   h('div',{className:'gr-thread__send'},h('span',{className:'gr-thread__hint'},'Ctrl + Enter to send'),h(Button,{size:'md',icon:'send',disabled:!draft.trim(),onClick:send},'Send'))));}
