'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useRef, useId } from '../runtime';
import type { DatePickerProps } from '../../types/index';
import { FormField } from './FormField';
import { Icon } from './Icon';
import { IconButton } from './IconButton';
import { useOutside } from './Popover';
import { cx } from '../utils';

export var MON=['January','February','March','April','May','June','July','August','September','October','November','December'];
export function pad(n){return (n<10?'0':'')+n;}
export function iso(d){return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());}
export function parseIso(s){if(!s)return null;var a=s.split('-');return new Date(+a[0],+a[1]-1,+a[2]);}
export function fmt(s){var d=parseIso(s);return d?pad(d.getDate())+' '+MON[d.getMonth()].slice(0,3)+' '+d.getFullYear():'';}
export function DatePicker(p: DatePickerProps){var auto=useId();var id=p.id||auto;var sv=useState(p.defaultValue||''),cur=sv[0],setCur=sv[1];var val=p.value!==undefined?p.value:cur;var so=useState(!!p.defaultOpen),open=so[0],setOpen=so[1];var ref=useRef(null);
 var base=parseIso(val)||parseIso(p.today)||new Date();var sm=useState(new Date(base.getFullYear(),base.getMonth(),1)),month=sm[0],setMonth=sm[1];var today=p.today||iso(new Date());
 useOutside(ref,open,function(){setOpen(false);});
 function pick(d){var v=iso(d);if(p.value===undefined)setCur(v);setOpen(false);if(p.onChange)p.onChange(v);var b=ref.current&&ref.current.querySelector('.gr-date__btn');if(b)b.focus();}
 var first=(month.getDay()+6)%7;var days=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();var cells=[];for(var i=0;i<first;i++)cells.push(null);for(var d=1;d<=days;d++)cells.push(new Date(month.getFullYear(),month.getMonth(),d));
 var weeks=[];for(var w=0;w<cells.length;w+=7)weeks.push(cells.slice(w,w+7));
 function out(dd){var v=iso(dd);return (p.min&&v<p.min)||(p.max&&v>p.max);}
 function gridKey(e){var t=e.target;if(!t.dataset||!t.dataset.day)return;var dd=parseIso(t.dataset.day);var step={ArrowLeft:-1,ArrowRight:1,ArrowUp:-7,ArrowDown:7}[e.key];if(!step)return;e.preventDefault();dd.setDate(dd.getDate()+step);if(dd.getMonth()!==month.getMonth())setMonth(new Date(dd.getFullYear(),dd.getMonth(),1));setTimeout(function(){var n=ref.current&&ref.current.querySelector('[data-day="'+iso(dd)+'"]');if(n)n.focus();},0);}
 var btn=h('button',{type:'button',id:id,className:'gr-date__btn','aria-haspopup':'dialog','aria-expanded':open,'aria-describedby':(p.error||p.helpText)?id+'-msg':undefined,disabled:p.disabled,onClick:function(){setOpen(!open);}},val?fmt(val):h('span',{className:'gr-ms__ph'},p.placeholder||'DD MMM YYYY'));
 return h('div',{ref:ref,className:'gr-pickwrap',onKeyDown:function(e){if(e.key==='Escape')setOpen(false);}},
  h(FormField,{id:id,label:p.label,required:p.required,helpText:p.helpText,error:p.error,size:p.size||'s',width:p.width,disabled:p.disabled,kind:'select',trailing:h('span',{className:'gr-field__deco'},h(Icon,{name:'calendar',size:20}))},btn),
  open?h('div',{role:'dialog','aria-label':'Choose date',className:'gr-cal'},
   h('div',{className:'gr-cal__head'},h(IconButton,{icon:'chevron--left',label:'Previous month',size:'sm',tooltip:false,onClick:function(){setMonth(new Date(month.getFullYear(),month.getMonth()-1,1));}}),h('span',{className:'gr-cal__month','aria-live':'polite'},MON[month.getMonth()]+' '+month.getFullYear()),h(IconButton,{icon:'chevron--right',label:'Next month',size:'sm',tooltip:false,onClick:function(){setMonth(new Date(month.getFullYear(),month.getMonth()+1,1));}})),
   h('table',{className:'gr-cal__grid',role:'grid',onKeyDown:gridKey},h('thead',null,h('tr',null,['Mo','Tu','We','Th','Fr','Sa','Su'].map(function(x){return h('th',{key:x,scope:'col',className:'gr-cal__dow'},x);}))),
    h('tbody',null,weeks.map(function(wk,wi){return h('tr',{key:wi},[0,1,2,3,4,5,6].map(function(k){var dd=wk[k];if(!dd)return h('td',{key:k});var v=iso(dd);var isSel=v===val;
     return h('td',{key:k},h('button',{type:'button','data-day':v,tabIndex:isSel||(!val&&v===today)?0:-1,disabled:out(dd),'aria-pressed':isSel,'aria-label':fmt(v),className:cx('gr-cal__day',isSel&&'is-selected',v===today&&'is-today'),onClick:function(){pick(dd);}},dd.getDate()));}));})))):null);}
