'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useId } from '../runtime';
import type { DocumentItemProps } from '../../types/index';
import { Icon } from './Icon';
import { IconButton } from './IconButton';
import { OverflowMenu } from './OverflowMenu';
import { StatusTag } from './StatusTag';
import { Tooltip } from './Tooltip';
import { cx } from '../utils';

export var DOC_ACT={edit:['edit','Edit document description'],view:['view','View document description'],open:['launch','Open document'],delete:['trash-can','Delete document'],upload:['upload','Upload document'],download:['download','Download document']};
export function DocumentItem(p: DocumentItemProps){var v=p.variant||'standard';var compact=!!p.compact;var so=useState(!!p.defaultExpanded),open=so[0],setOpen=so[1];var auto=useId();
 var acts=(p.actions||[]).map(function(a){var d=DOC_ACT[a.type]||[a.icon,a.label];return {icon:a.icon||d[0],label:a.label||d[1],onClick:a.onClick};});
 var showIcon=!compact&&v==='standard'||(!compact&&v==='under-review');
 var line2=v==='actions-required'?h('button',{type:'button',className:'gr-doc__acc','aria-expanded':open,'aria-controls':auto+'-p',onClick:function(){setOpen(!open);}},p.accordionLabel||'Affected Products',h(Icon,{name:'chevron--down',size:16,className:'gr-doc__chev'})):
  h(Tooltip,{label:[p.fileName,p.dateLabel,p.size].filter(Boolean).join(' • ')},h('span',{className:'gr-doc__meta',tabIndex:compact?0:undefined},[p.fileName,p.dateLabel,p.size].filter(Boolean).join(' • ')));
 var status=p.status?h(StatusTag,{status:p.status,label:p.statusLabel,compact:compact,size:'md',className:'gr-doc__status'}):null;
 var actions=acts.length?(compact||acts.length>3?h(OverflowMenu,{size:'sm',label:'Document actions',items:acts.map(function(a){return {label:a.label,onClick:a.onClick};})}):h('div',{className:'gr-doc__actions'},acts.map(function(a,i){return h(IconButton,{key:i,icon:a.icon,label:a.label,size:'md',onClick:a.onClick});}))):null;
 return h('div',{className:cx('gr-doc','gr-doc--'+v,compact&&'gr-doc--compact',open&&'is-open',p.className)},
  h('div',{className:'gr-doc__row'},
   showIcon?h(Icon,{name:'document--pdf',size:24,className:'gr-doc__icon'}):null,
   h('div',{className:'gr-doc__info'},h('span',{className:'gr-doc__type'},p.docType),line2),
   status,actions),
  v==='actions-required'&&open?h('div',{id:auto+'-p',className:'gr-doc__panel'},p.children):null);}
