'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { EmptyStateProps } from '../../types/index';
import { Icon } from './Icon';
import { cx } from '../utils';

export function EmptyState(p: EmptyStateProps){return h('div',{className:cx('gr-empty','gr-empty--'+(p.size||'md'),p.className)},p.icon?h('span',{className:'gr-empty__icon'},h(Icon,{name:p.icon,size:24})):null,h('div',{className:'gr-empty__title'},p.title),p.body?h('div',{className:'gr-empty__body'},p.body):null,p.action?h('div',{className:'gr-empty__action'},p.action):null);}
