'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useRef, useId } from '../runtime';
import type { FileUploadProps } from '../../types/index';
import { Icon } from './Icon';
import { IconButton } from './IconButton';
import { ProgressBar } from './ProgressBar';
import { cx } from '../utils';

export function fsize(b){return b>=1048576?(b/1048576).toFixed(1)+' MB':Math.max(1,Math.round(b/1024))+' KB';}
export function FileUpload(p: FileUploadProps){var auto=useId();var id=p.id||auto;var sf=useState(p.defaultFiles||[]),files=sf[0],setFiles=sf[1];var sd=useState(false),drag=sd[0],setDrag=sd[1];var inp=useRef(null);var max=(p.maxSizeMB||20)*1048576;
 function add(list){var arr=[].slice.call(list).map(function(f){var ok=f.size<=max;return {name:f.name,size:f.size,status:ok?'complete':'error',error:ok?null:'File is larger than '+(p.maxSizeMB||20)+' MB.'};});var next=p.multiple===false?arr.slice(0,1):files.concat(arr);setFiles(next);if(p.onFilesAdded)p.onFilesAdded(list);}
 function remove(i){var n=files.slice();var r=n.splice(i,1);setFiles(n);if(p.onRemove)p.onRemove(r[0]);}
 var ST={uploading:'Uploading…',scanning:'Scanning for viruses…',complete:null,error:null};
 return h('div',{className:cx('gr-upload',p.className)},
  p.label?h('div',{className:'gr-upload__label',id:id+'-label'},p.label,p.required?h('span',{className:'gr-req','aria-hidden':true},' *'):null):null,
  h('div',{className:'gr-upload__zone','data-state':drag?'dragover':undefined,onDragOver:function(e){e.preventDefault();setDrag(true);},onDragLeave:function(){setDrag(false);},onDrop:function(e){e.preventDefault();setDrag(false);add(e.dataTransfer.files);}},
   h(Icon,{name:'upload',size:24,className:'gr-upload__icon'}),
   h('div',{className:'gr-upload__text'},'Drag files here or ',h('button',{type:'button',className:'gr-upload__browse','aria-describedby':id+'-hint',onClick:function(){inp.current&&inp.current.click();}},'browse'),'.'),
   h('div',{className:'gr-upload__hint',id:id+'-hint'},p.hint||('PDF, DOC, XLS, JPG or PNG · up to '+(p.maxSizeMB||20)+' MB each')),
   h('input',{ref:inp,type:'file',className:'gr-sr',tabIndex:-1,multiple:p.multiple!==false,accept:p.accept,'aria-labelledby':id+'-label',onChange:function(e){add(e.target.files);e.target.value='';}})),
  files.length?h('ul',{className:'gr-upload__list','aria-label':'Files'},files.map(function(f,i){
   return h('li',{key:f.name+i,className:'gr-upload__file','data-status':f.status},
    h(Icon,{name:'document',size:20,className:'gr-upload__ficon'}),
    h('div',{className:'gr-upload__meta'},h('span',{className:'gr-upload__name'},f.name),
     f.status==='error'?h('span',{className:'gr-upload__err',role:'alert'},f.error||'Upload failed.'):h('span',{className:'gr-upload__sub'},(ST[f.status]?ST[f.status]+' · ':'')+(f.size!=null?fsize(f.size):'')),
     f.status==='uploading'?h(ProgressBar,{value:f.progress||0,size:'sm',label:'Uploading '+f.name,hideLabel:true}):null),
    f.status==='complete'?h(Icon,{name:'checkmark--filled',size:20,className:'gr-upload__ok',title:'Uploaded'}):f.status==='error'?h(Icon,{name:'warning--filled',size:20,className:'gr-upload__bad',title:'Error'}):null,
    h(IconButton,{icon:'close',label:'Remove '+f.name,size:'sm',onClick:function(){remove(i);}}));})):null);}
