'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { FormFieldProps } from '../../types/index';
import { cx } from '../utils';
import { tr } from '../tr';

export function FormField(p: FormFieldProps){var size=p.size||'m',kind=p.kind||'text';var showErr=!!p.error;var msg=showErr?p.error:p.helpText;
 return h('div',{className:cx('gr-field','gr-field--'+kind,'gr-field--'+size,showErr&&'is-error',p.disabled&&'is-disabled',p.className),style:p.width?{width:p.width}:undefined},
  h('div',{className:'gr-field__box'},
   h('div',{className:'gr-field__main'},
    p.label?h('label',{htmlFor:p.id,className:cx('gr-field__label',p.hideLabel&&'gr-sr')},tr(p.label),p.required?h('span',{className:'gr-req','aria-hidden':true},' *'):null):null,
    p.children),
   p.trailing?h('div',{className:'gr-field__trail'},p.trailing):null),
  msg?h('div',{id:p.id+'-msg',className:'gr-field__msg',role:showErr?'alert':undefined},tr(msg)):null);}
