'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { IconProps } from '../../types/index';
import { ICONS } from '../icons';
import { cx } from '../utils';

export function Icon(p: IconProps){var d=ICONS[p.name]||[];var s=p.size||16;return h('svg',{width:s,height:s,viewBox:'0 0 32 32',fill:'currentColor','aria-hidden':p.title?undefined:true,role:p.title?'img':undefined,'aria-label':p.title,className:cx('gr-icon',p.className),focusable:'false'},d.map(function(x,i){return h('path',{key:i,d:x[0],fill:x[1]});}));}
