'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { IconButtonProps } from '../../types/index';
import { Icon } from './Icon';
import { Tooltip } from './Tooltip';
import { cx, omit } from '../utils';

export function IconButton(p: IconButtonProps){var v=p.variant||'ghost',sz=p.size||'lg';
 var btn=h('button',Object.assign({type:'button'},omit(p,['variant','size','icon','label','className','tooltip','tooltipPlacement']),{'aria-label':p.label,className:cx('gr-btn','gr-iconbtn','gr-btn--'+v,'gr-btn--'+sz,p.className)}),h(Icon,{name:p.icon,size:20}));
 return p.tooltip===false?btn:h(Tooltip,{label:p.label,placement:p.tooltipPlacement},btn);}
