'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useEffect, useRef, useId } from '../runtime';
import type { LanguageSelectorProps } from '../../types/index';
import { Icon } from './Icon';
import { cx } from '../utils';

export var LANGS=[{code:'en',label:'English',short:'EN'},{code:'zh-Hant',label:'繁體中文',short:'中',hint:'Traditional Chinese'}];
export function LanguageSelector(p: LanguageSelectorProps){var langs=p.languages||LANGS;var auto=useId();var so=useState(!!p.defaultOpen),open=so[0],setOpen=so[1];var sv=useState(p.defaultValue||langs[0].code),cur=sv[0],setCur=sv[1];var val=p.value!==undefined?p.value:cur;var wrap=useRef(null);
 var active=langs.filter(function(l){return l.code===val;})[0]||langs[0];
 useEffect(function(){if(!open)return;function out(e){if(wrap.current&&!wrap.current.contains(e.target))setOpen(false);}document.addEventListener('mousedown',out);return function(){document.removeEventListener('mousedown',out);};},[open]);
 function pick(code){if(p.value===undefined)setCur(code);setOpen(false);if(p.onChange)p.onChange(code);var b=wrap.current&&wrap.current.querySelector('.gr-lang__trigger');if(b)b.focus();}
 function move(d){var els=[].slice.call(wrap.current.querySelectorAll('.gr-lang__item'));if(!els.length)return;var i=els.indexOf(document.activeElement);els[(i+d+els.length)%els.length].focus();}
 function onKey(e){if(e.key==='Escape'&&open){setOpen(false);var b=wrap.current.querySelector('.gr-lang__trigger');if(b)b.focus();}else if(e.key==='ArrowDown'){e.preventDefault();if(!open)setOpen(true);else move(1);}else if(e.key==='ArrowUp'){e.preventDefault();if(open)move(-1);}}
 return h('div',{ref:wrap,className:cx('gr-lang','gr-lang--'+(p.align||'end'),p.className),onKeyDown:onKey},
  h('button',{type:'button',className:cx('gr-lang__trigger',p.compact&&'gr-lang__trigger--compact'),'aria-haspopup':'menu','aria-expanded':open,'aria-controls':auto+'-menu','aria-label':'Language: '+active.label,onClick:function(){setOpen(!open);}},
   h(Icon,{name:'earth',size:20}),
   h('span',{className:'gr-lang__chip',lang:active.code,'aria-hidden':true},active.short),
   p.compact?null:h('span',{className:'gr-lang__label',lang:active.code},active.label),
   h(Icon,{name:'chevron--down',size:16,className:'gr-lang__chev'})),
  open?h('ul',{id:auto+'-menu',role:'menu','aria-label':'Choose language',className:'gr-menu gr-lang__menu'},langs.map(function(l){var sel=l.code===val;
   return h('li',{key:l.code,role:'none'},h('button',{type:'button',role:'menuitemradio','aria-checked':sel,lang:l.code,className:cx('gr-menu__item','gr-lang__item',sel&&'is-selected'),onClick:function(){pick(l.code);}},
    h('span',{className:'gr-lang__chip','aria-hidden':true},l.short),
    h('span',{className:'gr-lang__name'},h('span',null,l.label),l.hint?h('span',{className:'gr-lang__hint',lang:'en'},l.hint):null),
    sel?h(Icon,{name:'checkmark',size:16,className:'gr-lang__check'}):h('span',{className:'gr-lang__check'})));})):null);}
