'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { LogoProps } from '../../types/index';

export function Logo(p: LogoProps){return h('a',{href:p.href||'#',className:'gr-logo','aria-label':(p.siteName||'SGS')+' – home'},h('span',{className:'gr-logo__mark'},'SGS'),p.siteName?h('span',{className:'gr-logo__div','aria-hidden':true}):null,p.siteName?h('span',{className:'gr-logo__site'},h('span',{className:'gr-logo__name'},p.siteName),p.siteSub?h('span',{className:'gr-logo__sub'},p.siteSub):null):null);}
