'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useEffect, useRef, useId } from '../runtime';
import type { ModalProps } from '../../types/index';
import { Button } from './Button';
import { IconButton } from './IconButton';
import { cx } from '../utils';
import { tr } from '../tr';

export var FOCUSABLE='a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])';
export function Modal(p: ModalProps){var ref=useRef(null);var auto=useId();var tid=auto+'-title';
 useEffect(function(){if(!p.open||p.inline)return;var prev=document.activeElement;var el=ref.current;var f=el&&el.querySelectorAll(FOCUSABLE);if(f&&f.length)f[0].focus();var ov=document.body.style.overflow;document.body.style.overflow='hidden';
  return function(){document.body.style.overflow=ov;if(prev&&prev.focus)prev.focus();};},[p.open,p.inline]);
 if(!p.open)return null;
 function onKey(e){if(e.key==='Escape'&&p.onClose){e.stopPropagation();p.onClose();}
  if(e.key==='Tab'){var f=ref.current.querySelectorAll(FOCUSABLE);if(!f.length)return;var a=f[0],z=f[f.length-1];if(e.shiftKey&&document.activeElement===a){e.preventDefault();z.focus();}else if(!e.shiftKey&&document.activeElement===z){e.preventDefault();a.focus();}}}
 var pa=p.primaryAction,sa=p.secondaryAction;
 return h('div',{className:cx('gr-modal',p.inline&&'gr-modal--inline'),onMouseDown:function(e){if(e.target===e.currentTarget&&p.onClose&&p.dismissOnOverlay!==false)p.onClose();}},
  h('div',{ref:ref,role:'dialog','aria-modal':true,'aria-labelledby':tid,className:cx('gr-modal__dialog','gr-modal__dialog--'+(p.size||'md')),onKeyDown:onKey},
   h('div',{className:'gr-modal__head'},h('h2',{id:tid,className:'gr-modal__title'},tr(p.title)),p.onClose?h(IconButton,{icon:'close',label:tr('Close'),size:'md',tooltip:false,onClick:p.onClose}):null),
   h('div',{className:'gr-modal__body'},p.children),
   (pa||sa)?h('div',{className:'gr-modal__foot'},
    sa?h(Button,{variant:'ghost',onClick:sa.onClick},tr(sa.label)):null,
    pa?h(Button,{variant:p.danger?'danger':'primary',onClick:pa.onClick,disabled:pa.disabled},tr(pa.label)):null):null));}
