'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useRef, useId } from '../runtime';
import type { MultiSelectProps } from '../../types/index';
import { Checkbox } from './Checkbox';
import { FormField } from './FormField';
import { Icon } from './Icon';
import { useOutside } from './Popover';
import { cx } from '../utils';

export function MultiSelect(p: MultiSelectProps){var auto=useId();var id=p.id||auto;var opts=p.options||[];var sv=useState(p.defaultValue||[]),cur=sv[0],setCur=sv[1];var val=p.value!==undefined?p.value:cur;var so=useState(!!p.defaultOpen),open=so[0],setOpen=so[1];var ref=useRef(null);
 useOutside(ref,open,function(){setOpen(false);});
 function set(v){if(p.value===undefined)setCur(v);if(p.onChange)p.onChange(v);}
 function toggle(v){set(val.indexOf(v)>=0?val.filter(function(x){return x!==v;}):val.concat([v]));}
 var chosen=opts.filter(function(o){return val.indexOf(o.value)>=0;});
 var trigger=h('div',{className:'gr-ms__value'},
  h('button',{type:'button',id:id,className:'gr-ms__trigger','aria-haspopup':'listbox','aria-expanded':open,'aria-controls':id+'-list','aria-describedby':(p.error||p.helpText)?id+'-msg':undefined,disabled:p.disabled,onClick:function(){setOpen(!open);},onKeyDown:function(e){if(e.key==='Escape')setOpen(false);if(e.key==='ArrowDown'){e.preventDefault();setOpen(true);}}},
   chosen.length?h('span',{className:'gr-sr'},chosen.map(function(c){return c.label;}).join(', ')):h('span',{className:'gr-ms__ph'},p.placeholder||'Select...')),
  chosen.length?h('span',{className:'gr-ms__chips'},chosen.map(function(c){return h('span',{key:c.value,className:'gr-chip'},c.label,h('button',{type:'button',className:'gr-chip__x','aria-label':'Remove '+c.label,onClick:function(){toggle(c.value);}},h(Icon,{name:'close',size:16})));})):null);
 return h('div',{ref:ref,className:'gr-pickwrap',onKeyDown:function(e){if(e.key==='Escape')setOpen(false);}},
  h(FormField,{id:id,label:p.label,required:p.required,helpText:p.helpText,error:p.error,size:p.size,width:p.width,disabled:p.disabled,kind:'select',className:'gr-ms',trailing:h('span',{className:'gr-field__deco'},h(Icon,{name:'chevron--down',size:20}))},trigger),
  open?h('ul',{id:id+'-list',role:'listbox','aria-multiselectable':true,'aria-labelledby':id,className:'gr-list'},opts.map(function(o){var on=val.indexOf(o.value)>=0;
   return h('li',{key:o.value,role:'option','aria-selected':on,className:cx('gr-list__opt',on&&'is-selected')},h(Checkbox,{label:o.label,checked:on,onChange:function(){toggle(o.value);}}));})):null);}
