'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { NotificationBadgeProps } from '../../types/index';
import { cx } from '../utils';

export function NotificationBadge(p: NotificationBadgeProps){var c=p.count||0;var txt=c>(p.max||99)?(p.max||99)+'+':String(c);var show=p.dot||c>0;
 return h('span',{className:'gr-badge-wrap'},p.children,show?h('span',{className:cx('gr-badge',p.dot&&'gr-badge--dot'),'aria-hidden':true},p.dot?null:txt):null,show?h('span',{className:'gr-sr'},p.label||(c+' unread notifications')):null);}
