'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState } from '../runtime';
import type { NotificationCenterProps } from '../../types/index';
import { Button } from './Button';
import { Icon } from './Icon';
import { cx } from '../utils';

export var NTF_TYPE={status:['task','Status'],review:['edit','Review'],certificate:['calendar','Certificate'],assignment:['user--access','Assignment'],user:['user--multiple','Users'],document:['document','Document']};
export function NotificationCenter(p: NotificationCenterProps){var items=p.items||[];var st=useState(p.defaultTab||'unread'),tab=st[0],setTab=st[1];var sr=useState({}),read=sr[0],setRead=sr[1];
 function isUnread(n){return n.unread&&!read[n.id];}
 var unread=items.filter(isUnread);var list=tab==='unread'?unread:items;
 function markAll(){var r=Object.assign({},read);items.forEach(function(n){r[n.id]=true;});setRead(r);if(p.onMarkAllRead)p.onMarkAllRead();}
 function open(n){var r=Object.assign({},read);r[n.id]=true;setRead(r);if(p.onOpen)p.onOpen(n);}
 var groups=[];list.forEach(function(n){var g=n.group||'Earlier';var last=groups[groups.length-1];if(!last||last.name!==g)groups.push({name:g,items:[n]});else last.items.push(n);});
 return h('section',{className:cx('gr-ntf',p.className),'aria-label':p.label||'Notifications'},
  h('div',{className:'gr-ntf__head'},h('h2',{className:'gr-ntf__title'},p.title||'Notifications'),unread.length?h('button',{type:'button',className:'gr-ntf__markall',onClick:markAll},'Mark all as read'):null),
  h('div',{className:'gr-ntf__tabs',role:'tablist','aria-label':'Filter notifications'},
   [['unread','Unread',unread.length],['all','All',null]].map(function(t){var on=tab===t[0];return h('button',{key:t[0],type:'button',role:'tab','aria-selected':on,className:cx('gr-ntf__tab',on&&'is-on'),onClick:function(){setTab(t[0]);}},t[1],t[2]!=null?h('span',{className:'gr-ntf__count'},t[2]):null);})),
  h('div',{className:'gr-ntf__body',role:'tabpanel'},
   list.length===0?h('div',{className:'gr-ntf__empty'},h(Icon,{name:'checkmark--filled',size:24,className:'gr-ntf__empty-ic'}),h('span',{className:'gr-ntf__empty-t'},tab==='unread'?(p.emptyUnreadTitle||'You’re all caught up'):(p.emptyTitle||'No notifications yet')),h('span',{className:'gr-ntf__empty-b'},tab==='unread'?'New updates on your requests and documents appear here.':'Updates on your requests and documents will appear here.')):
   groups.map(function(g){return h('div',{key:g.name,className:'gr-ntf__group'},h('h3',{className:'gr-ntf__glabel'},g.name),
    h('ul',{className:'gr-ntf__list'},g.items.map(function(n){var t=NTF_TYPE[n.type]||NTF_TYPE.status;var un=isUnread(n);
     return h('li',{key:n.id},h('a',{href:n.href||'#',className:cx('gr-ntf__item',un&&'is-unread',n.tone&&('gr-ntf__item--'+n.tone)),onClick:function(){open(n);}},
      h('span',{className:'gr-ntf__ic','aria-hidden':true},h(Icon,{name:t[0],size:16})),
      h('span',{className:'gr-ntf__txt'},h('span',{className:'gr-ntf__t'},n.title),n.body?h('span',{className:'gr-ntf__b'},n.body):null,h('span',{className:'gr-ntf__meta'},[n.ref,n.time].filter(Boolean).join(' · '))),
      un?h('span',{className:'gr-ntf__dot'},h('span',{className:'gr-sr'},'Unread')):null));})));}),
   tab==='all'&&p.hasMore?h('div',{className:'gr-ntf__more'},h(Button,{variant:'ghost',size:'sm',onClick:p.onLoadMore},'Show older notifications')):null));}
