'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useEffect, useRef, useId } from '../runtime';
import type { OverflowMenuProps } from '../../types/index';
import { IconButton } from './IconButton';
import { cx } from '../utils';

export function OverflowMenu(p: OverflowMenuProps){var s=useState(!!p.defaultOpen),open=s[0],setOpen=s[1];var wrap=useRef(null);var auto=useId();var items=p.items||[];
 useEffect(function(){if(!open)return;function out(e){if(wrap.current&&!wrap.current.contains(e.target))setOpen(false);}document.addEventListener('mousedown',out);return function(){document.removeEventListener('mousedown',out);};},[open]);
 function focusItem(d){var els=[].slice.call(wrap.current.querySelectorAll('.gr-menu__item:not([disabled])'));if(!els.length)return;var i=els.indexOf(document.activeElement);var n=d==='first'?0:d==='last'?els.length-1:(i+d+els.length)%els.length;els[n].focus();}
 function onKey(e){if(e.key==='Escape'){setOpen(false);var b=wrap.current.querySelector('.gr-iconbtn');if(b)b.focus();}else if(e.key==='ArrowDown'){e.preventDefault();focusItem(1);}else if(e.key==='ArrowUp'){e.preventDefault();focusItem(-1);}else if(e.key==='Home'){e.preventDefault();focusItem('first');}else if(e.key==='End'){e.preventDefault();focusItem('last');}}
 return h('div',{ref:wrap,className:cx('gr-overflow','gr-overflow--'+(p.align||'end'),p.className),onKeyDown:onKey},
  h(IconButton,{icon:'overflow-menu--vertical',label:p.label||'More actions',size:p.size||'md',tooltip:!open,'aria-haspopup':'menu','aria-expanded':open,'aria-controls':auto+'-menu',onClick:function(){setOpen(!open);}}),
  open?h('ul',{id:auto+'-menu',role:'menu',className:'gr-menu'},items.map(function(it,i){return h('li',{key:i,role:'none'},h('button',{type:'button',role:'menuitem',disabled:it.disabled,className:cx('gr-menu__item',it.danger&&'gr-menu__item--danger'),onClick:function(){setOpen(false);if(it.onClick)it.onClick();}},it.label));})):null);}
