'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { React, h, useState, useEffect, useRef, useId } from '../runtime';
import type { PopoverProps } from '../../types/index';
import { cx } from '../utils';

export function useOutside(ref,open,close){useEffect(function(){if(!open)return;function f(e){if(ref.current&&!ref.current.contains(e.target))close();}document.addEventListener('mousedown',f);return function(){document.removeEventListener('mousedown',f);};},[open]);}
export function Popover(p: PopoverProps){var s=useState(!!p.defaultOpen),o=s[0],setO=s[1];var open=p.open!==undefined?p.open:o;var ref=useRef(null);var auto=useId();
 function set(v){if(p.open===undefined)setO(v);if(p.onOpenChange)p.onOpenChange(v);}
 useOutside(ref,open,function(){set(false);});
 var trig=React.cloneElement(React.Children.only(p.trigger),{'aria-expanded':open,'aria-haspopup':'dialog','aria-controls':auto,onClick:function(){set(!open);}});
 return h('span',{ref:ref,className:cx('gr-pop','gr-pop--'+(p.align||'start')),onKeyDown:function(e){if(e.key==='Escape'&&open){set(false);}}},trig,
  open?h('div',{id:auto,role:'dialog','aria-label':p.label||(typeof p.title==='string'?p.title:undefined),className:'gr-pop__panel',style:p.width?{width:p.width}:undefined},p.title?h('div',{className:'gr-pop__title'},p.title):null,p.children):null);}
