'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useId } from '../runtime';
import type { ProgressBarProps } from '../../types/index';
import { cx } from '../utils';

export function ProgressBar(p: ProgressBarProps){var v=Math.max(0,Math.min(100,p.value||0));var st=p.status||(v>=100?'success':'active');var auto=useId();
 return h('div',{className:cx('gr-prog','gr-prog--'+(p.size||'md'),p.className),'data-status':st},
  (p.label&&!p.hideLabel)?h('div',{className:'gr-prog__top'},h('span',{id:auto,className:'gr-prog__label'},p.label),h('span',{className:'gr-prog__val'},Math.round(v)+'%')):null,
  h('div',{className:'gr-prog__track',role:'progressbar','aria-valuemin':0,'aria-valuemax':100,'aria-valuenow':Math.round(v),'aria-labelledby':p.label&&!p.hideLabel?auto:undefined,'aria-label':p.hideLabel?p.label:undefined},h('div',{className:'gr-prog__fill',style:{width:v+'%'}})),
  p.helperText?h('div',{className:'gr-prog__help'},p.helperText):null);}
