'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { ReadinessRingProps } from '../../types/index';
import { cx } from '../utils';

export function ReadinessRing(p: ReadinessRingProps){var v=Math.max(0,Math.min(100,p.value||0));var big=p.size==='lg';var S=big?120:80,W=big?10:8,R=(S-W)/2,C=2*Math.PI*R;
 return h('div',{className:cx('gr-ring',big&&'gr-ring--lg',p.className),role:'img','aria-label':(p.label||'Readiness')+': '+Math.round(v)+'%'},
  h('span',{className:'gr-ring__viz'},h('svg',{width:S,height:S,viewBox:'0 0 '+S+' '+S,'aria-hidden':true},h('circle',{cx:S/2,cy:S/2,r:R,fill:'none',className:'gr-ring__track',strokeWidth:W}),h('circle',{cx:S/2,cy:S/2,r:R,fill:'none',className:'gr-ring__fill',strokeWidth:W,strokeLinecap:'round',strokeDasharray:(C*v/100)+' '+C,transform:'rotate(-90 '+S/2+' '+S/2+')'})),
   h('span',{className:'gr-ring__num'},Math.round(v)+'%')),
  (p.label||p.caption)?h('span',{className:'gr-ring__text'},p.label?h('span',{className:'gr-ring__label'},p.label):null,p.caption?h('span',{className:'gr-ring__cap'},p.caption):null):null);}
