'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState } from '../runtime';
import type { RequirementNavigatorProps } from '../../types/index';
import { EmptyState } from './EmptyState';
import { Icon } from './Icon';
import { ProgressBar } from './ProgressBar';
import { SearchInput } from './SearchInput';
import { Select } from './Select';
import { StatusTag } from './StatusTag';
import { cx } from '../utils';

export var RQ_ST={met:['completed','Met'],partial:['needs-description','Partially met'],notmet:['missing-info','Not met'],na:['draft','N/A'],fulfilled:['completed','Fulfilled'],review:['under-review','Under review'],missing:['missing-info','Missing evidence']};
export function RequirementNavigator(p: RequirementNavigatorProps){var groups=p.groups||[];var init={};(p.defaultExpanded||[]).forEach(function(k){init[k]=true;});var se=useState(init),exp=se[0],setExp=se[1];
 var ss=useState(p.defaultSelected||null),sel=ss[0],setSel=ss[1];var selected=p.selected!==undefined?p.selected:sel;
 var sq=useState(''),q=sq[0],setQ=sq[1];var sf=useState(p.defaultFilter||'all'),flt=sf[0],setF=sf[1];var labels=p.statusLabels||RQ_ST;
 function match(c){var okF=flt==='all'||(flt==='none'?!c.status:c.status===flt);var s=q.toLowerCase();var okQ=!s||(c.code+' '+c.title).toLowerCase().indexOf(s)>=0;return okF&&okQ;}
 function pick(c){if(p.selected===undefined)setSel(c.id);if(p.onSelect)p.onSelect(c.id,c);}
 var filterOpts=p.filterOptions||[{value:'all',label:'All'},{value:'none',label:'Not assessed'},{value:'notmet',label:'Not met'},{value:'partial',label:'Partially met'},{value:'met',label:'Met'},{value:'na',label:'N/A'}];
 var active=!!q||flt!=='all';
 return h('nav',{className:cx('gr-rnav',p.className),'aria-label':p.label||'Requirements'},
  p.framework?h('div',{className:'gr-rnav__fw'},
   h('div',{className:'gr-rnav__fw-top'},h('span',{className:'gr-rnav__fw-name'},p.framework.name),p.framework.progress!=null?h('span',{className:'gr-rnav__pct'},Math.round(p.framework.progress)+'%'):null),
   p.framework.progress!=null?h(ProgressBar,{value:p.framework.progress,size:'sm',label:p.framework.name+' progress',hideLabel:true}):null,
   p.framework.caption?h('span',{className:'gr-rnav__cap'},p.framework.caption):null):null,
  p.searchable===false?null:h('div',{className:'gr-dt__tools gr-rnav__tools'},
   h(SearchInput,{size:'s',width:'100%',placeholder:p.searchPlaceholder||'Search',label:'Search requirements',value:q,onChange:function(e){setQ(e.target.value);}}),
   p.filterable===false?null:h(Select,{label:'Filter by status',size:'s',width:120,value:flt,options:filterOpts,onChange:function(e,v){setF(v);}})),
  h('ul',{className:'gr-rnav__list'},groups.map(function(g){var kids=(g.children||[]).filter(match);var open=active?kids.length>0:!!exp[g.id];var inside=(g.children||[]).some(function(c){return c.id===selected;});
   if(active&&!kids.length)return null;var gid='rnav-'+g.id;
   return h('li',{key:g.id,className:'gr-rnav__group'},
    h('button',{type:'button',className:cx('gr-rnav__gbtn',inside&&'is-within'),'aria-expanded':open,'aria-controls':gid,onClick:function(){var n=Object.assign({},exp);n[g.id]=!exp[g.id];setExp(n);}},
     h(Icon,{name:'chevron--down',size:16,className:cx('gr-rnav__chev',open&&'is-open')}),
     g.code?h('span',{className:'gr-rnav__code'},g.code):null,
     h('span',{className:'gr-rnav__gtitle'},g.title),
     g.progress!=null?h('span',{className:'gr-rnav__pct'},Math.round(g.progress)+'%'):(g.count?h('span',{className:'gr-rnav__pct'},g.count):null),
     g.progress!=null?h('span',{className:'gr-rnav__gbar','aria-hidden':true},h('span',{style:{width:Math.max(0,Math.min(100,g.progress))+'%'}})):null),
    open?h('ul',{id:gid,className:'gr-rnav__items'},kids.map(function(c){var cur=c.id===selected;var st=c.status&&labels[c.status];
     return h('li',{key:c.id},h('button',{type:'button',className:cx('gr-rnav__item',cur&&'is-current'),'aria-current':cur?'true':undefined,onClick:function(){pick(c);}},
      h('span',{className:'gr-rnav__ititle'},h('span',{className:'gr-rnav__icode'},c.code),c.title),
      st?h(StatusTag,{status:st[0],label:st[1],size:'sm',className:'gr-rnav__tag'}):h('span',{className:'gr-rnav__none'},p.emptyStatusLabel||'Not assessed')));})):null);})),
  active&&!groups.some(function(g){return (g.children||[]).some(match);})?h(EmptyState,{size:'sm',title:'No matching requirements',body:'Try another search or filter.'}):null);}
