'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { SearchInputProps } from '../../types/index';
import { Icon } from './Icon';
import { TextInput } from './TextInput';
import { omit } from '../utils';

export function SearchInput(p: SearchInputProps){return h(TextInput,Object.assign({type:'search',label:'Search',hideLabel:!p.showLabel},omit(p,['showLabel']),{trailing:h('span',{className:'gr-field__deco'},h(Icon,{name:'search',size:20}))}));}
