'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { SeparatorProps } from '../../types/index';
import { cx } from '../utils';

export function Separator(p: SeparatorProps){var v=p.orientation==='vertical';return h('div',{role:p.decorative?'none':'separator','aria-orientation':v?'vertical':undefined,className:cx('gr-sep',v&&'gr-sep--v',p.className),style:p.spacing!==undefined?(v?{marginLeft:p.spacing,marginRight:p.spacing}:{marginTop:p.spacing,marginBottom:p.spacing}):undefined});}
