'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { SkeletonProps } from '../../types/index';
import { cx } from '../utils';

export function Skeleton(p: SkeletonProps){var v=p.variant||'text';if(v==='text'&&p.lines>1){var a=[];for(var i=0;i<p.lines;i++)a.push(h('span',{key:i,className:'gr-skel',style:{width:i===p.lines-1?'60%':'100%'}}));return h('span',{className:'gr-skel-stack','aria-hidden':true},a);}
 return h('span',{className:cx('gr-skel','gr-skel--'+v),'aria-hidden':true,style:{width:p.width,height:p.height}});}
