'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { TableProps } from '../../types/index';
import { cx } from '../utils';

export function cellValue(col,row){return col.render?col.render(row):row[col.key];}
export function Table(p: TableProps<any>){var cols=p.columns||[],rows=p.rows||[];var dens=p.density||'default';
 return h('div',{className:cx('gr-tbl',p.className),'data-density':dens},
  h('div',{className:'gr-tbl__scroll',style:p.maxHeight?{maxHeight:p.maxHeight}:undefined},
   h('table',{className:'gr-tbl__table'},
    p.caption?h('caption',{className:'gr-sr'},p.caption):null,
    h('thead',{className:'gr-tbl__head'},h('tr',null,cols.map(function(c){return h('th',{key:c.key,scope:'col',className:'gr-tbl__th','data-align':c.align||'start',style:c.width?{width:c.width}:undefined},c.header);}))),
    h('tbody',null,rows.map(function(r,i){return h('tr',{key:p.getRowId?p.getRowId(r):i,className:'gr-tbl__row'},cols.map(function(c){return h('td',{key:c.key,className:'gr-tbl__td','data-align':c.align||'start'},cellValue(c,r));}));})))));}
