'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { TagProps } from '../../types/index';
import { cx } from '../utils';

export function Tag(p: TagProps){return h('span',{className:cx('gr-tag','gr-tag--'+(p.tone||'neutral'),p.className)},p.children);}
