'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useId } from '../runtime';
import type { TextareaProps } from '../../types/index';
import { FormField } from './FormField';
import { FIELD_KEYS, useErrorRecovery } from './TextInput';
import { omit } from '../utils';

export function Textarea(p: TextareaProps){var auto=useId();var id=p.id||auto;var r=useErrorRecovery(p.error,p.onChange);
 var el=h('textarea',Object.assign({rows:4},omit(p,FIELD_KEYS),{id:id,className:'gr-field__input gr-field__textarea',disabled:p.disabled,required:p.required,'aria-invalid':r.error?true:undefined,'aria-describedby':(r.error||p.helpText)?id+'-msg':undefined,onChange:r.onChange}));
 return h(FormField,{id:id,label:p.label,required:p.required,helpText:p.helpText,error:r.error,size:p.size||'l',width:p.width,disabled:p.disabled,hideLabel:p.hideLabel,className:p.className,kind:'area'},el);}
