'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useEffect, useId } from '../runtime';
import type { TextInputProps } from '../../types/index';
import { FormField } from './FormField';
import { Icon } from './Icon';
import { omit } from '../utils';
import { tr } from '../tr';

export function useErrorRecovery(error,onChange){var s=useState(false),dirty=s[0],setDirty=s[1];useEffect(function(){setDirty(false);},[error]);
 return {error:dirty?undefined:error,onChange:function(e){if(error)setDirty(true);if(onChange)onChange(e);}};}
export var FIELD_KEYS=['id','label','required','helpText','error','size','width','disabled','hideLabel','className','trailing','onChange'];
export function TextInput(p: TextInputProps){var auto=useId();var id=p.id||auto;var r=useErrorRecovery(p.error,p.onChange);var sv=useState(false),shown=sv[0],setShown=sv[1];
 var isPw=p.type==='password';var trailing=p.trailing;
 if(isPw&&!trailing){trailing=h('button',{type:'button',className:'gr-field__iconbtn','aria-label':tr(shown?'Hide password':'Show password'),title:tr(shown?'Hide password':'Show password'),onClick:function(){setShown(!shown);}},h(Icon,{name:shown?'view':'view--off',size:20}));}
 var input=h('input',Object.assign({},omit(p,FIELD_KEYS.concat(['type'])),{id:id,type:isPw&&shown?'text':(p.type||'text'),className:'gr-field__input',disabled:p.disabled,required:p.required,'aria-invalid':r.error?true:undefined,'aria-describedby':(r.error||p.helpText)?id+'-msg':undefined,onChange:r.onChange}));
 return h(FormField,{id:id,label:p.label,required:p.required,helpText:p.helpText,error:r.error,size:p.size,width:p.width,disabled:p.disabled,hideLabel:p.hideLabel,className:p.className,trailing:trailing,kind:trailing?'icon':'text'},input);}
