'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { React, h, useState, useId } from '../runtime';
import type { TooltipProps } from '../../types/index';
import { cx } from '../utils';

export function Tooltip(p: TooltipProps){var auto=useId();var s=useState(false),open=s[0],setOpen=s[1];var shown=p.open!==undefined?p.open:open;var id=auto+'-tip';
 var child=React.Children.only(p.children);
 var trig=React.cloneElement(child,{'aria-describedby':shown?id:child.props['aria-describedby']});
 return h('span',{className:cx('gr-tip','gr-tip--'+(p.placement||'top')),onMouseEnter:function(){setOpen(true);},onMouseLeave:function(){setOpen(false);},onFocus:function(){setOpen(true);},onBlur:function(){setOpen(false);},onKeyDown:function(e){if(e.key==='Escape')setOpen(false);}},
  trig,shown?h('span',{id:id,role:'tooltip',className:'gr-tip__bubble'},p.label):null);}
