'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h } from '../runtime';
import type { TopBarProps } from '../../types/index';
import { Avatar } from './Avatar';
import { Button } from './Button';
import { Icon } from './Icon';
import { IconButton } from './IconButton';
import { LanguageSelector } from './LanguageSelector';
import { Link } from './Link';
import { Logo } from './Logo';
import { NotificationBadge } from './NotificationBadge';
import { NotificationCenter } from './NotificationCenter';
import { Popover } from './Popover';
import { Separator } from './Separator';
import { Tag } from './Tag';
import { cx } from '../utils';

export function TopBar(p: TopBarProps){var v=p.variant||'home';var compact=!!p.compact;
 var right=null;
 if(v==='landing'){right=h('div',{className:'gr-top__right'},h('nav',{'aria-label':'Main',className:'gr-top__nav'},(p.links||['Services','Contact Us','How It Works']).map(function(l,i){return h('a',{key:i,href:'#',className:'gr-top__link'},l);})),h(Button,{size:'md',variant:'primary'},p.loginLabel||'Log In'),h(LanguageSelector,{compact:true}));}
 else if(v==='login'){right=p.showLanguage===false?null:h('div',{className:'gr-top__right'},h(LanguageSelector,{compact:compact}));}
 else{var n=p.notifications||0;right=h('div',{className:'gr-top__right'},
   p.onLanguageChange?h(LanguageSelector,{compact:compact,value:p.language||'en',onChange:p.onLanguageChange}):null,
   (p.homeLinks||[{label:'Request Applications',icon:'folder',brand:true},{label:'Communications',icon:'events'}]).map(function(l,i){return compact?h(IconButton,{key:i,icon:l.icon||'folder',label:l.label,size:'md'}):h('a',{key:i,href:l.href||'#',className:cx('gr-top__link',l.brand&&'gr-top__link--brand')},l.label);}),
   p.notificationItems?(function(){var un=p.notificationItems.filter(function(x){return x.unread;}).length;
     return h(Popover,{align:'end',label:'Notifications',width:420,defaultOpen:p.notificationsOpen,trigger:h('button',{type:'button',className:'gr-top__bell','aria-label':'Notifications'+(un?', '+un+' unread':'')},h(Icon,{name:'notification',size:20}),un?h('span',{className:'gr-badge','aria-hidden':true},un>99?'99+':String(un)):null)},
      h(NotificationCenter,{items:p.notificationItems,defaultTab:p.notificationsTab,hasMore:p.notificationsHasMore,onLoadMore:p.onNotificationsLoadMore,onOpen:p.onNotificationOpen,onMarkAllRead:p.onMarkAllRead}));})():
   h(NotificationBadge,{count:n,label:n+' unread notifications'},h(IconButton,{icon:'notification',label:'Notifications',size:'md'})),
   h(Popover,{align:'end',label:'Account',width:240,trigger:h('button',{type:'button',className:'gr-top__user','aria-label':'Account: '+(p.userName||'User')},h(Avatar,{name:p.userName,size:'md'}))},
    h('div',{className:'gr-top__acct'},h('div',{className:'gr-top__acct-name'},p.userName||'User'),p.userEmail?h('div',{className:'gr-top__acct-mail'},p.userEmail):null),
    h(Separator,{spacing:8}),h('div',{className:'gr-top__acct-links'},(p.accountLinks||[{label:'Profile'},{label:'Settings'}]).map(function(l,i){return h(Link,{key:i,href:l.href||'#',onClick:l.onClick?function(e){e.preventDefault();l.onClick();}:undefined},l.label);}),h(Link,{href:p.signOutHref||'#',onClick:p.onSignOut?function(e){e.preventDefault();p.onSignOut();}:undefined},p.signOutLabel||'Sign out'))));}
 return h('header',{'data-theme':p.tone==='dark'?'inverse':undefined,className:cx('gr-top','gr-top--'+v,compact&&'gr-top--compact',p.tone==='dark'&&'gr-top--dark',p.className)},h('div',{className:'gr-top__left'},h(Logo,{siteName:p.siteName,siteSub:p.siteSub}),p.badge?h(Tag,{tone:'neutral'},p.badge):null),right);}
