'use client';
// Generated by scripts/port-bundle.mjs from design-system/graphite/dist/components/bundle.js. Do not edit by hand.
import { h, useState, useRef } from '../runtime';
import type { TreeViewProps } from '../../types/index';
import { Icon } from './Icon';
import { cx } from '../utils';

export function TreeView(p: TreeViewProps){var items=p.items||[];var init={};(p.defaultExpanded||[]).forEach(function(k){init[k]=true;});var se=useState(init),exp=se[0],setExp=se[1];var ss=useState(p.defaultSelected||null),sel=ss[0],setSel=ss[1];var selected=p.selected!==undefined?p.selected:sel;var ref=useRef(null);
 var flat=[];(function walk(list,lvl,parent){list.forEach(function(it){flat.push({it:it,lvl:lvl,parent:parent});if(it.children&&exp[it.id])walk(it.children,lvl+1,it.id);});})(items,1,null);
 var sf=useState(flat.length?flat[0].it.id:null),foc=sf[0],setFoc=sf[1];
 function choose(it){if(p.selected===undefined)setSel(it.id);if(p.onSelect)p.onSelect(it.id,it);}
 function focusId(idv){setFoc(idv);setTimeout(function(){var n=ref.current&&ref.current.querySelector('[data-id="'+idv+'"]');if(n)n.focus();},0);}
 function onKey(e){var i=flat.findIndex(function(f){return f.it.id===foc;});if(i<0)return;var f=flat[i];var hasKids=f.it.children&&f.it.children.length;
  if(e.key==='ArrowDown'&&i<flat.length-1){e.preventDefault();focusId(flat[i+1].it.id);}
  else if(e.key==='ArrowUp'&&i>0){e.preventDefault();focusId(flat[i-1].it.id);}
  else if(e.key==='ArrowRight'){e.preventDefault();if(hasKids&&!exp[f.it.id]){var n=Object.assign({},exp);n[f.it.id]=true;setExp(n);}else if(hasKids&&flat[i+1])focusId(flat[i+1].it.id);}
  else if(e.key==='ArrowLeft'){e.preventDefault();if(hasKids&&exp[f.it.id]){var n2=Object.assign({},exp);n2[f.it.id]=false;setExp(n2);}else if(f.parent)focusId(f.parent);}
  else if(e.key==='Enter'||e.key===' '){e.preventDefault();choose(f.it);}}
 function toggle(idv){var n=Object.assign({},exp);n[idv]=!exp[idv];setExp(n);}
 function render(list,lvl){return list.map(function(it,idx){var kids=it.children&&it.children.length;var open=!!exp[it.id];
  return h('li',{key:it.id,role:'treeitem','aria-level':lvl,'aria-setsize':list.length,'aria-posinset':idx+1,'aria-expanded':kids?open:undefined,'aria-selected':selected===it.id,className:'gr-tree__item'},
   h('div',{'data-id':it.id,tabIndex:foc===it.id?0:-1,className:cx('gr-tree__row',selected===it.id&&'is-selected'),style:{paddingLeft:8+(lvl-1)*24},onClick:function(){setFoc(it.id);choose(it);},onFocus:function(){setFoc(it.id);}},
    kids?h('span',{className:cx('gr-tree__chev',open&&'is-open'),onClick:function(e){e.stopPropagation();toggle(it.id);}},h(Icon,{name:'chevron--right',size:16})):h('span',{className:'gr-tree__chev gr-tree__chev--leaf'}),
    it.icon?h(Icon,{name:it.icon,size:16,className:'gr-tree__icon'}):null,
    h('span',{className:'gr-tree__label'},it.label),it.meta?h('span',{className:'gr-tree__meta'},it.meta):null),
   kids&&open?h('ul',{role:'group',className:'gr-tree__group'},render(it.children,lvl+1)):null);});}
 return h('ul',{ref:ref,role:'tree','aria-label':p.label||'Tree',className:cx('gr-tree',p.className),onKeyDown:onKey},render(items,1));}
